### ISSUE TITLE
Cardav authentication broken after upgrade to version 8.1.1 from 8.0.x

### ISSUE THREAD

**Issue by mschaaf** [owncloud/contacts#1038]
I use the following url for syncing contacts to my mobile phone:

https://<server>/owncloud/remote.php/carddav/addressbooks/<user name>/kontakte

Before my upgrade to version 8.1.1 this worked very well. After the upgrade it stopped working With the following error

```
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
<s:sabredav-version>2.1.6</s:sabredav-version>
<s:exception>Sabre\DAVACL\Exception\NeedPrivileges</s:exception>
<s:message>
User did not have the required privileges ({DAV:}read) for path "addressbooks/<username>/kontakte"
</s:message>
<d:need-privileges>
<d:resource>
<d:href>
/owncloud/remote.php/carddav/addressbooks/<username>/kontakte
</d:href>
<d:privilege>
<d:read/>
</d:privilege>
</d:resource>
</d:need-privileges>
</d:error>
```

**Comment by gvde** [comment]
Use the template from the [contribution guidelines](https://github.com/owncloud/contacts/blob/master/CONTRIBUTING.md)
The URL you wrote
https:///owncloud/remote.php/carddav/addressbooks//kontakte
is definitely wrong...

**Comment by mschaaf** [comment]
> The URL you wrote ... is definitely wrong...

Excuse, I didn't quote the placeholders. I corrected it.

**Comment by mschaaf** [comment]
I found this in the logs too
```
{"reqId":"raylW49YWntybY4rBVci","remoteAddr":"185.10.151.147","app":"core","message":"Adding default user backend WEBDAVAUTH.","level":0,"time":"2015-09-07T06:27:55+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/carddav\/addressbooks\/martin\/kontakte"}
{"reqId":"raylW49YWntybY4rBVci","remoteAddr":"185.10.151.147","app":"carddav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No basic authentication headers were found\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(149): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(122): OC\\\\Connector\\\
```

**Comment by mschaaf** [comment]
In the apache logs for the same request like above I have:

```
185.10.151.147 - - [07/Sep/2015:09:09:42 +0200] "PROPFIND /.well-known/carddav HTTP/1.1" 301 4608 "-" "Mozilla/5.0"
185.10.151.147 - - [07/Sep/2015:09:09:42 +0200] "PROPFIND /owncloud/remote.php/carddav/ HTTP/1.1" 401 1223 "-" "Mozilla/5.0"
185.10.151.147 - username [07/Sep/2015:09:09:42 +0200] "PROPFIND /owncloud/remote.php/carddav/ HTTP/1.1" 207 1548 "-" "Mozilla/5.0"
185.10.151.147 - username [07/Sep/2015:09:09:43 +0200] "PROPFIND /owncloud/remote.php/carddav/principals/username/ HTTP/1.1" 207 1404 "-" "Mozilla/5.0"
185.10.151.147 - username [07/Sep/2015:09:09:43 +0200] "PROPFIND /owncloud/remote.php/carddav/addressbooks/username/ HTTP/1.1" 207 1848 "-" "Mozilla/5.0"

```

**Comment by gvde** [comment]
Please use the template...

**Comment by RealRancor** [comment]
@mschaaf Disable the "User backend using remote HTTP servers" if you don't use it.

**Comment by j-ed** [comment]
After upgrading my server to ownCloud 8.1.3 I realized that "401 No basic authentication headers were found" exceptions are logged when address books are accessed from an iPhone with iOS 8.4.1.
The URL I'm using is the recommended one for iOS devices: `ADDRESS/remote.php/carddav/principals/username`. I do not have the "User backend using remote HTTP servers" enabled on my server and the synchronization worked without problems with the contacts app v0.3.0.19 and ownCloud v8.0.8
```
...,"app":"carddav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No basic authentication headers were found\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(149): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#1 \\\/var\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(122): OC\\\\Connector\\\\Sabre\\\\Auth->auth(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#2 \\\/var\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(118): OC\\\\Connector\\\\Sabre\\\\Auth->authenticate(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#3 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#6 \\\/var\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/var\\\/www\\\/htdocs\\\/owncloud\\\/apps2\\\/contacts\\\/appinfo\\\/remote.php(84): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/htdocs\\\/owncloud\\\/remote.php(132): require_once('\\\/var\\\/www\\\/htdocs...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php\",\"Line\":70}","level":0,"time":"2015-09-22 14:13:56+02:00",
"method":"OPTIONS","url":"\/owncloud\/remote.php\/carddav\/principals\/juergen\/addressbooks\/juergen\/gemeinsame_kontakte\/"}

```

**Comment by RealRancor** [comment]
@j-ed Please create a new issue by using the issue template as you're error looks different than the OP here is getting.

**Comment by j-ed** [comment]
@RealRancor done. https://github.com/owncloud/contacts/issues/1056
