### ISSUE TITLE
SabreDAV exceptions are logged when address books are accessed from an iPhone

### ISSUE THREAD

**Issue by j-ed** [owncloud/contacts#1056]
## Expected behavior
No exceptions should happen when address books are accessed from an iPhone.

## Current behavior
The following exceptions are logged when address books are accessed from an iPhone
with iOS 8.4.1. The URL used to access the address books is `ADDRESS/remote.php/carddav/principals/username`. This kind of problem didn't appear with the previous contacts app v0.3.0.19 and ownCloud v8.0.8.
```
...,"app":"carddav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No basic authentication headers were found\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(149): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#1 \\\/var\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(122): OC\\\\Connector\\\\Sabre\\\\Auth->auth(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#2 \\\/var\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(118): OC\\\\Connector\\\\Sabre\\\\Auth->authenticate(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#3 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#6 \\\/var\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/var\\\/www\\\/htdocs\\\/owncloud\\\/apps2\\\/contacts\\\/appinfo\\\/remote.php(84): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/htdocs\\\/owncloud\\\/remote.php(132): require_once('\\\/var\\\/www\\\/htdocs...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php\",\"Line\":70}","level":0,"time":"2015-09-22 14:13:56+02:00", "method":"OPTIONS","url":"\/owncloud\/remote.php\/carddav\/principals\/juergen\/addressbooks\/juergen\/gemeinsame_kontakte\/"}

...,"app":"carddav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 404 Node with name addressbooks was not found\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(76): Sabre\\\\CalDAV\\\\Principal\\\\User->getChild('addressbooks')\\n#1 \\\/var\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(71): Sabre\\\\DAV\\\\Tree->getNodeForPath('principals\\\/juer...')\\n#2 \\\/var\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(71): Sabre\\\\DAV\\\\Tree->getNodeForPath('principals\\\/juer...')\\n#3 \\\/var\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(920): Sabre\\\\DAV\\\\Tree->getNodeForPath('principals\\\/juer...')\\n#4 \\\/var\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(327): Sabre\\\\DAV\\\\Server->getPropertiesForPath('principals\\\/juer...', Array, 0)\\n#5 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPropfind(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#7 \\\/var\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PROPFIND', Array)\\n#8 \\\/var\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#9 \\\/var\\\/www\\\/htdocs\\\/owncloud\\\/apps2\\\/contacts\\\/appinfo\\\/remote.php(84): Sabre\\\\DAV\\\\Server->exec()\\n#10 \\\/var\\\/www\\\/htdocs\\\/owncloud\\\/remote.php(132): require_once('\\\/var\\\/www\\\/htdocs...')\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Principal\\\/User.php\",\"Line\":65}","level":0,"time":"2015-09-22 14:13:56+02:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/carddav\/principals\/juergen\/addressbooks\/juergen\/gemeinsame_kontakte\/"}
```
## Steps to reproduce
Open the owncloud log and search for exceptions if address books are accessed from an iPhone.

#### Server Configuration
OS: Linux 3.2.67
Web server: Apache2 2.4.12
Database: MySQL 5.1.73
PHP version: 5.4.42
ownCloud version: 8.1.3
Contacts app version: 0.4.0.0

#### Client Configuration
Operating system: iOS v8.4.1

**Comment by gvde** [comment]
The URL is incorrect: /owncloud/remote.php/carddav/principals/juergen/addressbooks/juergen/gemeinsame_kontakte/
The correct URL would be /owncloud/remote.php/carddav/addressbooks/juergen/gemeinsame_kontakte/
Which exact URL did you use to set up the cardav account on your iPhone? How did you set it up exactly?

**Comment by j-ed** [comment]
@gvde Please check the user manual https://doc.owncloud.org/server/8.1/user_manual/pim/sync_ios.html which is stating that the URL `ADDRESS/owncloud/remote.php/carddav/principals/username` should be entered in Mail, Contacts, Calendar -> Contacts -> Extended settings -> Account-URL.
Exactly the given URL has been entered as I first set-up CardDAV access with previous ownCloud versions. The available address books were shown and selected which automatically results in the given address. This URL has worked with all previous ownCloud versions, except v8.1.3. Has the URL be changed in the latest version?

**Comment by gvde** [comment]
Is that the complete URL shown in the advanced settings of the carddav account? Because on iOS 9 it will always add the / at the end.
How about setting up a new carddav account with this URL? Works fine for me...
You can use ```curl -u username -X PROPFIND http://.../username/``` on your server to find all the addressbooks for the user...

**Comment by j-ed** [comment]
Sorry, you' re right. There is indead a trailing slash at the end of the URL: `ADDRESS/owncloud/remote.php/carddav/principals/username/`. I've now deleted the CardDAV configuration on the iPhone and recreated it with the URL `ADDRESS/owncloud/remote.php/carddav/addressbooks/juergen/` and all existing contacts were added again. Nevertheless the URL in iPhone extended account settings dialog was automatically rewritten to `ADDRESS/owncloud/remote.php/carddav/principals/username/` at the end.

Unfortunately that doesn't solve the problem that there are still "`401 No basic authentication headers were found`" messages logged. Today I realized that these messages are not only logged for an iPhone but also for e.g. Thunderbird (Inverse SOGo Connector 24.0.2) access.
It seems that I'm still able to edit contact information and a synchronization is taking place, except that the message is logged. (BTW: It is also logged for CalDAV accesses).

**Comment by gvde** [comment]
The 401 errors are no problem. That's normal. The client first tries to access the URL without authentication headers and only authenticates after it receives the 401. The 401 tells the client it needs to authenticate. If you check the webserver logs you'll see two access lines: first without username but 401 code, next the same URL but with user name and a 200 code...

**Comment by j-ed** [comment]
@gvde I understand, but wouldn't it be a good idea to catch that kind of error instead of causing a SabreDAV exception?! This kind of exceptions are flooding the log file and it is difficult to focus on real problems which might be logged.

**Comment by RealRancor** [comment]
Such errors could be also caused by apache with mod_fcgid for example which is not passing the auth headers at all. So i think its hard to distinguish between them.

**Comment by gvde** [comment]
@j-ed I think the 401 exception is only logged at loglevel 0 aka DEBUG. DEBUG loglevel is always verbose and logging a lot of information which may or may not be helpful. Thus, I think it's fully O.K. to log those 401s because they may indicate a problem, even if it's not most of the time. If you have debug logging enabled you can easily filter out those lines from your logs for further analysis if you are sure it's not related.
If I try to find the cause of a problem in the debug logs I usually grep for the request id anyway as I know which requests is the one I need to look at.
And in production, you shouldn't use debug loglevel anyway. It's generally not secure and not recommended to run a production system at debug loglevel.
