### ISSUE TITLE
Contacts not working with Mac OS El Capitan Address Book existing configuration

### ISSUE THREAD

**Issue by qirtaiba** [owncloud/contacts#1080]
Note: I don't think this is a duplicate of #1058 because I did not remove and re-add my configuration, it is an old configuration that was working under previous versions of OS X. Also the error message differs.

### Steps to reproduce
1. Open Address Book app on Mac OS 10.11 with existing ownCloud configuration from pre-upgrade.
2. Warning triangle appears and any Contacts that you add don't appear in ownCloud.

### Expected behaviour
Address Book app works as normal.

### Actual behaviour
Open Address Book, click the warning triangle and it says "The operation couldn’t be completed. (CoreDAVErrorDomain error 3.)"

### Server configuration
**Operating system**: Debian 8

**Web server:** Apache 2.4.10

**Database:** MySQL 5.5

**PHP version:** 5.6.7

**ownCloud version:** ownCloud 8.2

**Updated from an older ownCloud or fresh install:** Updated

**List of activated apps:**

```
Enabled:
  - activity: 2.1.3
  - calendar: 0.8.0
  - contacts: 0.5.0.0
  - files: 1.2.0
  - files_external: 0.3.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - grauphel: 0.6.1
  - mozilla_sync: 1.4
  - music: 0.3.7
  - tasks: 0.5.1
  - templateeditor: 0.1
  - updater: 0.6
Disabled:
  - encryption
  - external
  - files_locking
  - notifications
  - provisioning_api
  - search_lucene
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "oc1e0d67c158",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "www.malcolm.id.au"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "3rdpartyroot": "\/var\/www\/owncloud\/",
        "3rdpartyurl": "\/3rdparty",
        "dbtype": "mysql",
        "version": "8.2.0.12",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "mail_smtpmode": "php",
        "mail_domain": "malcolm.id.au",
        "mail_from_address": "owncloud",
        "preview_libreoffice_path": "\/usr\/bin\/soffice",
        "theme": "",
        "maintenance": false,
        "overwritewebroot": "\/owncloud",
        "overwrite.cli.url": "\/owncloud",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "logfile": "\/var\/log\/owncloud.log",
        "loglevel": "0",
        "trashbin_retention_obligation": "auto"
    }
}```

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Firefox 41

**Operating system:** Mac OS 10.11

### Logs
#### ownCloud log (data/owncloud.log)
```
{"reqId":"A0htZdaFLDFGNQdWNUsJ","remoteAddr":"79.97.87.240","app":"caldav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No basic authentication headers were found\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(148): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(121): OC\\\\Connector\\\\Sabre\\\\Auth->auth(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(118): OC\\\\Connector\\\\Sabre\\\\Auth->authenticate(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#3 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/calendar\\\/appinfo\\\/remote.php(67): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/owncloud\\\/remote.php(137): require_once('\\\/var\\\/www\\\/ownclo...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php\",\"Line\":70}","level":0,"time":"2015-10-23T14:49:10+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/caldav\/calendars\/terminus\/"}
```

**Comment by gvde** [comment]
The apache log should show if and what the clients tries to access...

**Comment by qirtaiba** [comment]
Oh, yes.  I was looking at the error log.  Here's from the access log:

```
79.97.87.240 - terminus [23/Oct/2015:08:10:41 -0700] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 1113 "-" "Mozilla/5.0 (Macintosh) mirall/2.0.1"
```

**Comment by gvde** [comment]
But that's not a line from OS X Contacts. It's a webdav access from "mirall/2.0.1".

Please post the logs which are generated when you start the OS X Contacts application...

**Comment by qirtaiba** [comment]
Oh, sorry.  How about this:

```
79.97.87.240 - - [23/Oct/2015:08:18:49 -0700] "PROPFIND /.well-known/carddav HTTP/1.1" 404 4280 "-" "Mac OS X/10.11.1 (15B42) AddressBook/1679"

79.97.87.240 - - [23/Oct/2015:08:18:50 -0700] "PROPFIND / HTTP/1.1" 200 46106 "-" "Mac OS X/10.11.1 (15B42) AddressBook/1679"
79.97.87.240 - - [23/Oct/2015:08:18:51 -0700] "PROPFIND /principals/ HTTP/1.1" 404 4277 "-" "Mac OS X/10.11.1 (15B42) AddressBook/1679"
```

**Comment by qirtaiba** [comment]
Also .htaccess in my ownCloud directory has this (I didn't add it, it was always there):

```
  RewriteRule ^\.well-known/carddav /remote.php/carddav/ [R=301,L]
  RewriteRule ^\.well-known/caldav /remote.php/caldav/ [R=301,L]
```

**Comment by gvde** [comment]
This is a dup of #1058. OS X only tries the .well-known address and you have no working redirect. Thus it doesn't find it anymore. I don't know why OS X screwed up the internal settings for an already working CardDAV account but the logs suggest it did anyway.
Either way for Apple to fix the preferences dialog windows or set up a redirect for the .well-known address as a workaround.
Either way, this is #1058 all over...

**Comment by RealRancor** [comment]
Ref for an request at core to detect such broken .well-known URLs: https://github.com/owncloud/core/issues/20012
