### ISSUE TITLE
REPORT addressbook-query 404

### ISSUE THREAD

**Issue by kousu** [owncloud/contacts#1092]
I am using 8.1.1 and finding that [`REPORT addressbook-query`](http://tools.ietf.org/html/rfc6352#section-8.6) is misbehaving.

The CardDAV spec says both PROPFIND and REPORT addressbook-query should do basically the same thing, as do the [SabreDAV docs](http://sabre.io/dav/building-a-carddav-client/). But they aren't:

```
$ openssl s_client -quiet -connect my.owndrive.com:443
depth=3 C = SE, O = AddTrust AB, OU = AddTrust External TTP Network, CN = AddTrust External CA Root
verify return:1
depth=2 C = GB, ST = Greater Manchester, L = Salford, O = COMODO CA Limited, CN = COMODO RSA Certification Authority
verify return:1
depth=1 C = GB, ST = Greater Manchester, L = Salford, O = COMODO CA Limited, CN = COMODO RSA Domain Validation Secure Server CA
verify return:1
depth=0 OU = Domain Control Validated, OU = EssentialSSL Wildcard, CN = *.owndrive.com
verify return:1
PROPFIND https://my.owndrive.com/remote.php/carddav/addressbooks/kousu/contacts/ HTTP/1.1
Authorization: Basic xxxxxxxxxxxxxxxxxxxxxxxxx=
Host: my.owndrive.com
Connection: close
HTTP/1.1 207 Multi-Status
Date: Sat, 31 Oct 2015 00:49:31 GMT
Content-Type: application/xml; charset=utf-8
Transfer-Encoding: chunked
Connection: close
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src *; font-src 'self' data:; media-src *; connect-src *
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Frame-Options: Sameorigin
X-Robots-Tag: none
Set-Cookie: PHPSESSIDI=xxxxxxxxxxxxxxxxxxxxxxx; path=/; secure; HttpOnly
X-Sabre-Version: 2.1.6
Vary: Brief,Prefer
DAV: 1, 3, extended-mkcol, addressbook, access-control, calendarserver-principal-property-search
Server: Apache

3544
<?xml version="1.0" encoding="utf-8"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:card="urn:ietf:params:xml:ns:carddav"><d:response><d:href>/remote.php/carddav/addressbooks/kousu/contacts/</d:href><d:propstat><d:prop><d:getlastmodified>Fri, 30 Oct 2015 04:50:02 GMT</d:getlastmodified><d:resourcetype><d:collection/><card:addressbook/></d:resourcetype></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response><d:response><d:href>/remote.php/carddav/addressbooks/kousu/contacts/a4b48ac12e.vcf</d:href><d:propstat><d:prop><d:getlastmodified>Mon, 19 Jan 2015 03:59:09 GMT</d:getlastmodified><d:getcontentlength>371</d:getcontentlength><d:resourcetype/><d:getetag>"43a9f3f8c2e23a1f1e19e3be6bc0436f"</d:getetag><d:getcontenttype>text/vcard; charset=utf-8</d:getcontenttype></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response><d:response><d:href>/remote.php/carddav/addressbooks/kousu/contacts/1079352a-7a63-4622-86ac-7e5409ff18c9.vcf</d:href><d:propstat><d:prop><d:getlastmodified>Wed, 01 Jul 2015 21:46:21 GMT</d:getlastmodified><d:getcontentlength>4403</d:getcontentlength><d:resourcetype/><d:getetag>"5b31341c4e897667efb5d11709de7e1d"</d:getetag><d:getcontenttype>text/vcard; charset=utf-8</d:getcontenttype></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response><d:response><d:href>/remote.php/carddav/addressbooks/kousu/contacts/https%253A%252F%252Fkousu%2540my.owndrive.com%252Fremote.php%252Fcarddav%252Faddressbooks%252Fkousu%252Fcontacts%252F3e977fee-f0fa-4a95-8779-14249c3b2862.vcf.vcf</d:href><d:propstat><d:prop><d:getlastmodified>Sat, 11 Jan 2014 00:06:15 GMT</d:getlastmodified><d:getcontentlength>733</d:getcontentlength><d:resourcetype/><d:getetag>"6b8c57e884192c360441c6c64e622b0c"</d:getetag><d:getcontenttype>text/vcard; charset=utf-8</d:getcontenttype></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response><d:response><d:href>/remote.php/carddav/addressbooks/kousu
[.....]
```

```
$ openssl s_client -quiet -connect my.owndrive.com:443
depth=3 C = SE, O = AddTrust AB, OU = AddTrust External TTP Network, CN = AddTrust External CA Root
verify return:1
depth=2 C = GB, ST = Greater Manchester, L = Salford, O = COMODO CA Limited, CN = COMODO RSA Certification Authority
verify return:1
depth=1 C = GB, ST = Greater Manchester, L = Salford, O = COMODO CA Limited, CN = COMODO RSA Domain Validation Secure Server CA
verify return:1
depth=0 OU = Domain Control Validated, OU = EssentialSSL Wildcard, CN = *.owndrive.com
verify return:1
REPORT https://my.owndrive.com/remote.php/carddav/addressbooks/kousu/contacts/ HTTP/1.1
Authorization: Basic xxxxxxxxxxxxxxxxxxxxxxxxx=
Host: my.owndrive.com
Connection: close
Depth: 1
Content-Type: application/xml; charset=utf-8
Content-Length: 190

<card:addressbook-query xmlns:d="DAV:" xmlns:card="urn:ietf:params:xml:ns:carddav">
    <d:prop>
        <d:getetag />
        <card:address-data />
    </d:prop>
</card:addressbook-query>

HTTP/1.1 404 Not Found
Date: Sat, 31 Oct 2015 00:47:27 GMT
Content-Type: application/xml; charset=utf-8
Transfer-Encoding: chunked
Connection: close
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src *; font-src 'self' data:; media-src *; connect-src *
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Frame-Options: Sameorigin
X-Robots-Tag: none
Set-Cookie: PHPSESSIDI=xxxxxxxxxxxxxxxxxxxxxxx; path=/; secure; HttpOnly
X-Sabre-Version: 2.1.6
Server: Apache

ff
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:sabredav-version>2.1.6</s:sabredav-version>
  <s:exception>Sabre\DAV\Exception\NotFound</s:exception>
  <s:message>Card not found</s:message>
</d:error>

0
```

I ran into this because DAVDroid 0.9 rewrote their DAV implementation to switch from PROPFIND to REPORT addressbook-query and this [broke my contacts sync](https://forums.bitfire.at/topic/830/0-9-0-4-regression-with-owndrive).

So, that error is bubbling up from [here](https://github.com/owncloud/contacts/blob/905b69c26e89c397d74f9e7b3dab980f96d2638c/lib/carddav/addressbook.php#L211), but I am not familiar with the code and it looks like whatever is going on crosses over into https://github.com/owncloud/core *and* https://github.com/fruux/sabre-dav/ and back again. Judging from old issues here, REPORT addressbook-query is supposed to be fully supported, so I have no idea what's going on. (I'm also using ownCloud via owndrive.com, which means I can't debug this; it might even just be a configuration issue, and if you can tell that it is that please tell me so my hoster can fix it.)

**Comment by gvde** [comment]
Please use the template from the contribution guidelines.

In all cases, there have been a lot of fixes since 8.1.1 thus an update seems to be in order.

I have just tried the your report on my oc 8.2 server with contacts 0.5.0.0 and it returns a multi-status with all cards.

**Comment by mpuls** [comment]
I ran into the same problem like kousu. Thus, I updated my oc to 8.2 and contacts to 0.5.0.0 in order to see if it gets any better. Unfortunately, it didn't.

Nevertheless, at least in my case, the origin of the problem were several contacts with a UID like `UID:AAMkAGY3NTUyYWMwLTZmNjEtNDQwMi1hNjBkLTZmMDczNGE2NzU3MQBGAAAAAAAbcxze/PU
 /Srux3ey2goyQBwDlwvDlHgKiQqHNPQVhZ+KKAAAAAlNbAADRH5XZKInsTar5qbiRMw2WAB0J3
 Z6eAAA=` while _good_ ones are supposed to look like `UID:b662d561-2737-4ffa-9caa-40920344232f`, I guess.

Therefore, I exported all my contacts, removed the strange looking UIDs and imported the vcf-file again. Hence, the contacts get a new UID and the synchronization works fine since then.

**Comment by matmo** [comment]
Thanks @mpuls, this fix works for me as well

**Comment by kousu** [comment]
My hoster is now running ownCloud 8.2.2 and my contacts are syncing properly again. I don't know if this means it's REPORT addressbook-query is working now or what, but for now I'll close this.

**Comment by kousu** [comment]
Oh wait, hang on, it's still screwy. Most of my contacts synced but I got this error message from DAVDroid, and the UIDs it lists are indeed missing from my phone:

```
SYNCHRONIZATION INFO
Synchronization phase: 9
Account name: kousu@my.owndrive.com
Authority: com.android.contacts

HTTP REQUEST:
REPORT https://my.owndrive.com/remote.php/carddav/addressbooks/kousu/contacts/
Content-Length: 1319
Content-Type: application/xml; charset=utf-8
Depth: 0

<?xml version='1.0' encoding='UTF-8' ?><CARD:addressbook-multiget xmlns="DAV:" xmlns:CARD="urn:ietf:params:xml:ns:carddav"><prop><getcontenttype /><getetag /><CARD:address-data content-type="text/vcard" version="4.0"
/></prop><href>/remote.php/carddav/addressbooks/kousu/contacts/https://kousu@my.owndrive.com/remote.php/carddav/addressbooks/kousu/contacts/3e977fee-f0fa-4a95-8779-14249c3b2862.vcf.vcf</href><href>/remote.php/carddav/addressbooks/kousu/contacts/5e3aa29c-73e6-4e35-888d-f570a22d782d.vcf</href><href>/remote.php/carddav/addressbooks/kousu/contacts/ebccff14-c6fe-4f80-9d06-6992a6c56916.vcf</href><href>/remote.php/carddav/addressbooks/kousu/contacts/C5AB9FFE-E3A0-0001-FB87-4A602D70ED00.vcf</href><href>/remote.php/carddav/addressbooks/kousu/contacts/9284fed6-1df6-4ef2-a226-f7718db4bef2.vcf</href><href>/remote.php/carddav/addressbooks/kousu/contacts/f18d37d9-2181-4c43-8752-2864290fa45c.vcf</href><href>/remote.php/carddav/addressbooks/kousu/contacts/682390cf-768b-404f-b43e-a0fd541057b3.vcf</href><href>/remote.php/carddav/addressbooks/kousu/contacts/490315d1-2eec-4fd6-b572-6d6dbba33303.vcf</href><href>/remote.php/carddav/addressbooks/kousu/contacts/a4b48ac12e.vcf</href><href>/remote.php/carddav  
/addressbooks/kousu/contacts/dcd01903-842d-45ad-8d90-2116feb2c95e.vcf</href></CARD:addressbook-multiget>

HTTP RESPONSE:
http/1.1 404 Not Found
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Connection: keep-alive
Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *
Content-Type: application/xml; charset=utf-8
Date: Sun, 03 Jan 2016 03:45:17 GMT
Expires: Thu, 19 Nov 1981 08:52:00 GMT
OkHttp-Received-Millis: 1451792718104
OkHttp-Selected-Protocol: http/1.1
OkHttp-Sent-Millis: 1451792717846
Pragma: no-cache
Server: Apache
Transfer-Encoding: chunked
X-Content-Type-Options: nosniff
X-Frame-Options: Sameorigin
X-Robots-Tag: none
X-Sabre-Version: 2.1.7
X-XSS-Protection: 1; mode=block

<?xml version="1.0" encoding="utf-8"?>[LF]
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">[LF]
  <s:sabredav-version>2.1.7</s:sabredav-version>[LF]
  <s:exception>Sabre\DAV\Exception\NotFound</s:exception>[LF]
  <s:message>Card not found</s:message>[LF]
</d:error>[LF]


STACK TRACE:
at.bitfire.dav4android.exception.NotFoundException: 404 Not Found
at.bitfire.dav4android.exception.NotFoundException: 404 Not Found
	at at.bitfire.dav4android.DavResource.checkStatus(DavResource.java:273)
	at at.bitfire.dav4android.DavResource.checkStatus(DavResource.java:286)
	at at.bitfire.dav4android.DavAddressBook.multiget(DavAddressBook.java:117)
	at at.bitfire.davdroid.syncadapter.ContactsSyncManager.downloadRemote(ContactsSyncManager.java:176)
	at at.bitfire.davdroid.syncadapter.SyncManager.performSync(SyncManager.java:182)
	at at.bitfire.davdroid.syncadapter.ContactsSyncAdapterService$ContactsSyncAdapter.onPerformSync(ContactsSyncAdapterService.java:52)
	at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:259)

SOFTWARE INFORMATION
DAVdroid version: 0.9.1.2 (86) Sat Jan 02 22:50:37 EST 2016
Installed from: org.fdroid.fdroid
JB Workaround installed: no

CONFIGURATION
System-wide synchronization: automatically
Account: kousu@my.owndrive.com
  Address book sync. interval: 1440 min
  Calendar     sync. interval: 1440 min
  OpenTasks    sync. interval: 1440 min

SYSTEM INFORMATION
Android version: 4.4.4
```

**Comment by gvde** [comment]
This looks like a duplicate of #1103

**Comment by kousu** [comment]
For future reference, in case someone finds this and needs to repair their own database manually as well:

I exported my contacts from ownCloud. I opened Contacts.vcf and found a bunch of lines like
```
UID:https://kousu@my.owndrive.com/remote.php/carddav/addressbooks/kousu/con
 tacts/3e977fee-f0fa-4a95-8779-14249c3b2862.vcf
```
(the exporter wrapped them so you can't simply sed them out of the way)
I manually searched from every "UID:https://" and erased each. I deleted the address book from ownCloud and reimported the modified .vcf. Now ownCloud has filled in the UIDs I erased with new UUIDs, and sync works perfectly.

Not all of my UIDs are UUIDs. Here's a snippet of my list to demonstrate:
```
UID:465f1bade1
UID:99ca9241-59a4-4d20-be02-2c1e5b77cef1
UID:c0002fbc-c13a-4fb5-91d9-2e5a37a41006
[...]
UID:68e44b88-b41e-416b-97b1-619531f77c19
UID:C5ABA031-C1F0-0001-2B12-1F1017E04EF0
UID:cc16b261dc
UID:C5ABA031-C210-0001-8E30-1A2A1822B470
[...]
UID:ebccff14-c6fe-4f80-9d06-6992a6c56916
UID:01E4E102-912221BA-65E47851
UID:21975C21-BBA7C97C-F2EE7D89
UID:061d1183-4448-42a7-b6aa-2e2478659993
```
however, apparently only the URL ones were giving trouble, exactly as in #1103.

**Comment by alpenjon** [comment]
I can't believe I finally found the solution to this sync problem. I also had the problem with the UID's containing https://[USER]@[OWNDRIVESERVER] information, where my [USER] was from a previous, meanwhile non-existent Owncloud account.

Exporting the .vcf from Owncloud, deleting those UID's in the exported file, deleting my contacts on Ownccloud and then re-uploading the fixed .vcf back to Owncloud did the job.

Thank you so much!
