### ISSUE TITLE
Fatal carddav This resource only supports valid vcard data

### ISSUE THREAD

**Issue by timreeves** [owncloud/contacts#1095]
For some (unknown) time ownCloud 8.1.3 is regularly (every couple of hours) producing a couple of messages like this titled "Fatal carddav":

`Exception: {"Message":"HTTP\/1.1 415 This resource only supports valid vcard data. Parse error: This parser only supports VCARD and VCALENDAR files","Code":0,"Trace":"#0 \/var\/www\/vhosts\/gemeinwohl.info\/owncloud.lasslos.net\/3rdparty\/sabre\/dav\/lib\/CardDAV\/Plugin.php(384): OCA\\Contacts\\CardDAV\\Plugin->validateVCard('BEGIN:VLIST\\r\\nPR...', false)\n#1 [internal function]: Sabre\\CardDAV\\Plugin->beforeCreateFile('addressbooks\/Ti...', 'BEGIN:VLIST\\r\\nPR...', Object(OCA\\Contacts\\CardDAV\\AddressBook), false)\n#2 \/var\/www\/vhosts\/gemeinwohl.info\/owncloud.lasslos.net\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#3 \/var\/www\/vhosts\/gemeinwohl.info\/owncloud.lasslos.net\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1051): Sabre\\Event\\EventEmitter->emit('beforeCreateFil...', Array)\n#4 \/var\/www\/vhosts\/gemeinwohl.info\/owncloud.lasslos.net\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(513): Sabre\\DAV\\Server->createFile('addressbooks\/Ti...', Resource id #32, NULL)\n#5 [internal function]: Sabre\\DAV\\CorePlugin->httpPut(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#6 \/var\/www\/vhosts\/gemeinwohl.info\/owncloud.lasslos.net\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#7 \/var\/www\/vhosts\/gemeinwohl.info\/owncloud.lasslos.net\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:PUT', Array)\n#8 \/var\/www\/vhosts\/gemeinwohl.info\/owncloud.lasslos.net\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#9 \/var\/www\/vhosts\/gemeinwohl.info\/owncloud.lasslos.net\/apps\/contacts\/appinfo\/remote.php(84): Sabre\\DAV\\Server->exec()\n#10 \/var\/www\/vhosts\/gemeinwohl.info\/owncloud.lasslos.net\/remote.php(132): require_once('\/var\/www\/vhosts...')\n#11 {main}","File":"\/var\/www\/vhosts\/gemeinwohl.info\/owncloud.lasslos.net\/apps\/contacts\/lib\/carddav\/plugin.php","Line":58} `

I don't find much help in the error message - the only thing that I thought may help to locate an invalid Vcard-Format was "Resource id #32" - but my oc_contacts_cards has no record with ID 32.

I have never touched the address book tables manually, so at some point ownCloud must have written an invalid vcard itself...

So my questions:
* How can I locate the corrupted Vcard? (Assuming one is)
* Is this possibly not a corrupted Vcard but a bug in ownCloud?
* Is there any test suite, plugin, whatever, for debugging address book data?

Thanks!
Tim

**Comment by gvde** [comment]
I would say the broken card starts with line "BEGIN:VLIST".

However, this is a PUT call...

You should your web server access log for which client does what at that time.

And as usually: use the template from the contribution guidelines. All the basic information would be available at one place...

**Comment by timreeves** [comment]
Sorry about the poor reporting - but your tip got me to the solution (I think): I'm using SOGo Connector with Thunderbird (the only option with Thunderbird) and recently I created a couple of contact groups - which (only) SOGo Connector exports as VLIST - that'll be the invalid PUT data. The connector does that because SOGo Server can and wants to handle it - and there's no option in Connector to turn this behaviour off.

This is a known issue with the Connector since 2012, and never fixed:
http://www.sogo.nu/bugs/view.php?id=1851

The code is still there, in sogo-connector-31.0.1/chrome/content/sogo-connector/general/vcards.utils.js, which is dated 26.09.2013 - so it does'nt look like we can rely on a solution from SOGo.

So my question to the active team at ownCloud: Could you possibly build in something to quietly skip over any BEGIN:VLIST from SOGo Connector?

Many thanks for a great product!!!
Tim Reeves
