### ISSUE TITLE
[REGRESSION] carddav sync stopped working since upgrading to 8.1 and newer

### ISSUE THREAD

**Issue by gladiac** [owncloud/contacts#1098]
Hello,

I've recently updated to 8.1 and yesterday to 8.2. Since then I'm not able to synchronize contacts anymore. It doesn't matter which client I use. The error is always the same:

Message: "Only vCard 2.1, 3.0 and 4.0 are supported for the input data"

```
{"reqId":"Jhmryf2VMMiz3qRE6pp7","remoteAddr":"2.242.32.114","app":"carddav","message":"Exception: {\"Message\":\"Only vCard 2.1, 3.0 and 4.0 are supported for the input data\",\"Exception\":\"InvalidArgumentException\",\"Code\":0,\"Trace\":\"#0 /owncloud/3rdparty/sabre/vobject/lib/Component/VCard.php(175): Sabre\VObject\VCardConverter->convert(Object(OCA\Contacts\VObject\VCard), 5)\\n#1 /owncloud/3rdparty/sabre/dav/lib/CardDAV/Plugin.php(898): Sabre\VObject\Component\VCard->convert(5)\\n#2 /owncloud/3rdparty/sabre/dav/lib/CardDAV/Plugin.php(328): Sabre\CardDAV\Plugin->convertVCard('BEGIN:VCARD\r\nEM...', 'vcard3')\\n#3 /owncloud/3rdparty/sabre/dav/lib/CardDAV/Plugin.php(255): Sabre\CardDAV\Plugin->addressbookMultiGetReport(Object(DOMDocument))\\n#4 [internal function]: Sabre\CardDAV\Plugin->report('{urn:ietf:param...', Object(DOMDocument), 'addressbooks/as...')\\n#5 /owncloud/3rdparty/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#6 /owncloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php(710): Sabre\Event\EventEmitter->emit('report', Array)\\n#7 [internal function]: Sabre\DAV\CorePlugin->httpReport(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))\\n#8 /owncloud/3rdparty/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#9 /owncloud/3rdparty/sabre/dav/lib/DAV/Server.php(469): Sabre\Event\EventEmitter->emit('method:REPORT', Array)\\n#10 /owncloud/3rdparty/sabre/dav/lib/DAV/Server.php(254): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))\\n#11 /owncloud/apps/contacts/appinfo/remote.php(84): Sabre\DAV\Server->exec()\\n#12 /owncloud/remote.php(137): require_once('/owcloud...')\\n#13 {main}\",\"File\":\"/owncloud/3rdparty/sabre/vobject/lib/VCardConverter.php\",\"Line\":40}","level":4,"time":"2015-11-05T12:26:55+00:00"}
```

I've triggered the log using kaddressbook from KDE. I get the same error with davdroid.

**Comment by gvde** [comment]
1. Please use the template from the contribution guidelines for issue submission.
2. Make sure to update the contacts app.
3. Check that all cards in your database have a correct VERSION property...

**Comment by gladiac** [comment]
The contacts app is up2date. I've updated yesterday. Why don't owncloud tell me if a vcard is wrong?

**Comment by gladiac** [comment]
A lot of entries do not have:

´´´
BEGIN:VCARD
VERSION:3.0
...
´´´

they only have:

´´´
BEGIN:VCARD
FN: Bob
´´´

This worked with owncloud 8.0. Do you expect all owncloud users to manually edit thouands of contact entries in the database?

Why can the webinterface display them?

**Comment by gvde** [comment]
Again: please use the template from the contribution guidelines. It tells you how to extract exact information about your installation. You say 'contacts app is up2date' but noone can verify that it really is...

owncloud comes with a new sabre version now which is more stringent in regard to rfc compliance. It won't accept so much as it used to.

And, yes, generally if the user imported broken cards into any service, it's the user's responsibility to fix the cards, because many automated repair functions often make things worse as they don't fully know what the original intention was.

So if you are sure that all those cards are in fact 3.0 and not 2.1 or 4.0, you should fix them in the database and make sure the cards all comply with the rfc.

The web interface just reads the data and presents it. For that it doesn't really matter which version it is.

However, for an multiget request like that of yours, the server has to convert all cards to a specific vcard version as specified by the client and for that conversion to work reliably, it is necessary that the original is compliant with the version it is supposed to be. Otherwise, it may actually damage the already broken card and make things worse or irreparable.

**Comment by gladiac** [comment]
Would it be possible to add a warning in the web interface if the vcard doesn't have a version set or uses an unsupported version by the carddav protocol.

This way a user can go through his contacts, create a new one and delete the problematic one.
