### ISSUE TITLE
Can't load contacts after contacts import - "Allowed memory size of bytes exhausted"

### ISSUE THREAD

**Issue by CriticalNoob** [owncloud/contacts#1117]
### Steps to reproduce
1. Import a moderately large contact list (Around 150 contacts) ( .vcf file) 
2. Try to load contact

### Expected behavior
Contacts should be displayed.

### Actual behavior
Spinning wheel forever and error 500

### Server configuration
**Operating system**:
Ubuntu 14.04
**Web server:**
Apache 2
**Database:**
Mysql
**PHP version:**
5.5
**ownCloud version:** (see ownCloud admin page)
8.2
**Updated from an older ownCloud or fresh install:**
Fresh install
**List of activated apps:**
Enabled:
  - activity: 2.1.3
  - calendar: 0.8.1
  - contacts: 0.5.0.0
  - files: 1.2.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - notifications: 0.1.0
  - provisioning_api: 0.3.0
  - templateeditor: 0.1
  - updater: 0.6
Disabled:
  - encryption
  - external
  - files_external
  - gallery
  - user_external
  - user_ldap

**The content of config/config.php:**

{
    "system": {
        "instanceid": "ocjjeva77i4v",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "example.com",
            "www.example.com"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/example.com",
        "dbtype": "mysql",
        "version": "8.2.2.2",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "asset-pipeline.enabled": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "loglevel": 0
    }
}

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Relevant ?
Safari

**Operating system:**
Mac os X.11

#### Web server error log
Clean

#### ownCloud log (data/owncloud.log)

{"reqId":"a7LUAHv8JCX6Fk50ZfZl","remoteAddr":"88.168.110.81","app":"core","message":"OC\\Tags::getFavorites, exception: Could not find category \"_$!<Favorite>!$_\"","level":0,"time":"2015-12-28T13:08:54+00:00","method":"GET","url":"\/index.php\/apps\/contacts\/groups\/"}
{"reqId":"nTR2rGgIk1z6SVuk2fNg","remoteAddr":"88.168.110.81","app":"contacts","message":"OCA\\Contacts\\Contact::retrieve Error parsing carddata  for: 1518 End of document reached prematurely","level":3,"time":"2015-12-28T13:08:55+00:00","method":"GET","url":"\/index.php\/apps\/contacts\/addressbook\/local\/5\/contacts"}
{"reqId":"nTR2rGgIk1z6SVuk2fNg","remoteAddr":"88.168.110.81","app":"contacts","message":"OCA\\Contacts\\Contact::retrieve Error parsing carddata  for: 1518 End of document reached prematurely","level":3,"time":"2015-12-28T13:08:55+00:00","method":"GET","url":"\/index.php\/apps\/contacts\/addressbook\/local\/5\/contacts"}
{"reqId":"nTR2rGgIk1z6SVuk2fNg","remoteAddr":"88.168.110.81","app":"contacts","message":"OCA\\Contacts\\Contact::retrieve Error parsing carddata  for: 1518 End of document reached prematurely","level":3,"time":"2015-12-28T13:08:55+00:00","method":"GET","url":"\/index.php\/apps\/contacts\/addressbook\/local\/5\/contacts"}
{"reqId":"nTR2rGgIk1z6SVuk2fNg","remoteAddr":"88.168.110.81","app":"PHP","message":"Allowed memory size of 536870912 bytes exhausted (tried to allocate 498073600 bytes) at \/var\/www\/owncloud\/apps\/contacts\/lib\/utils\/jsonserializer.php#86","level":3,"time":"2015-12-28T13:09:05+00:00","method":"GET","url":"\/index.php\/apps\/contacts\/addressbook\/local\/5\/contacts"}

#### Browser log

[Error] Failed to load resource: the server responded with a status of 500 (Internal Server Error) (contacts, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (jquery.min.map, line 0)

#### Edit :
Weird thing, in chrome dev tool, network, I get : 
contacts	GET	500	xhr	a59ca11f2d5674e459c130137b587d1c.js:6	217 MB

And it is still downloading at full bandwidth, what is happening ?!?

repost of : https://github.com/owncloud/core/issues/21384

**Comment by CriticalNoob** [comment]
I tried something else :
I added my owncloud carddav account to my Apple Adressbook and manually added my contact to it.
It seems to have added some contacts but after a while I get : 
`CoreDAVHTTPStatusErrorDomain erreur 500 on the mac.`

On the owncloud log I get a bunchload of 
`{"reqId":"m\/CG9KcNZKWtps1r7XSK","remoteAddr":"88.168.xx.xx","app":"PHP","message":"Undefined index: addressBookId at \/var\/www\/owncloud\/apps\/contacts\/lib\/hooks.php#109","level":3,"time":"2015-12-30T07:31:36+00:00"}`

And while the contact are synchronized I can browse them on the contact page but after a while I get in the log :

`{"reqId":"NASg7p1bfQlLVG640ANJ","remoteAddr":"88.168.x.x":"carddav","message":"Exception: {\"Message\":\"End of document reached prematurely\",\"Exception\":\"Sabre\\\\VObject\\\\EofException\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(133): Sabre\\\\VObject\\\\Parser\\\\MimeDir->readLine()\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(63): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parseDocument()\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Reader.php(44): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parse('BEGIN:VCARD??VE...', 0)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CardDAV\\\/Plugin.php(894): Sabre\\\\VObject\\\\Reader::read('BEGIN:VCARD??VE...')\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CardDAV\\\/Plugin.php(328): Sabre\\\\CardDAV\\\\Plugin->convertVCard('BEGIN:VCARD??VE...', 'vcard3')\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CardDAV\\\/Plugin.php(255): Sabre\\\\CardDAV\\\\Plugin->addressbookMultiGetReport(Object(DOMDocument))\\n#6 [internal function]: Sabre\\\\CardDAV\\\\Plugin->report('{urn:ietf:param...', Object(DOMDocument), 'addressbooks\\\/fr...')\\n#7 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#8 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(710): Sabre\\\\Event\\\\EventEmitter->emit('report', Array)\\n#9 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpReport(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#10 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#11 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:REPORT', Array)\\n#12 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#13 \\\/var\\\/www\\\/owncloud\\\/apps\\\/contacts\\\/appinfo\\\/remote.php(84): Sabre\\\\DAV\\\\Server->exec()\\n#14 \\\/var\\\/www\\\/owncloud\\\/remote.php(137): require_once('\\\/var\\\/www\\\/ownclo...')\\n#15 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php\",\"Line\":250}","level":4,"time":"2015-12-30T07:32:31+00:00"}`

**Comment by CriticalNoob** [comment]
Ok I found something :

I ran
`SELECT * 
FROM  `oc_contacts_cards` 
WHERE  `carddata` NOT LIKE  "%END:VCARD%"
LIMIT 0 , 30`

And found one contact that looked like : 
`(3069, 12, 'Nicolas ', 'BEGIN:VCARD\r\nVERSION:3.0\r\nPRODID:-//ownCloud//NONSGML Contacts 0.5.0.0//EN\r\nN:;Nicolas ', 'da24e9d5-dce3-438a-a264-39714cc5cb6c.vcf', 1451460738);`
And everything is working back after I deleted him from the mysql base.

I can reproduce it with a .vcf file and the same contact is crashing the import :
`BEGIN:VCARD
VERSION:3.0
VERSION:3.0
VERSION:3.0
VERSION:3.0
VERSION:3.0
PRODID:-//ownCloud//NONSGML Contacts 0.5.0.0//EN
PRODID:-//Sabre//Sabre VObject 3.4.7//EN
PRODID:-//Apple Inc.//iOS 7.0.4//EN
N:;Nicolas `

**Comment by gvde** [comment]
>  BEGIN:VCARD
VERSION:3.0
VERSION:3.0
VERSION:3.0
VERSION:3.0
VERSION:3.0
PRODID:-//ownCloud//NONSGML Contacts 0.5.0.0//EN
PRODID:-//Sabre//Sabre VObject 3.4.7//EN
PRODID:-//Apple Inc.//iOS 7.0.4//EN
N:;Nicolas

That card is severly broken. Fix the card before import.

The multiple VERSION and PRODID values have been fixed by #1068 (and #1054 for master branch). Apply the patch and report back in the pull request if that fixes your problem. We need some people to test those pull requests to get them into the next release...

You may want to go through the other open (and recently closed) pull requests for some more fixes...

**Comment by CriticalNoob** [comment]
The multiple version is not the problem,  but I found what it is.

My contact had an emoji in his name for some reason, here is his card before import :

`BEGIN:VCARD
VERSION:3.0
PRODID:-//Apple Inc.//iOS 7.0.4//EN
N:;Nicolas 👾;;;
FN:Nicolas 👾
TEL;type=CELL;type=VOICE;type=pref:06 xx xx xx xx
X-SOCIALPROFILE;type=facebook;x-user=xxxrid=xxx
 x-displayname=X Xl:http://www.facebook.com/xxx
REV:2014-05-02T17:39:42Z
END:VCARD

I remove the emoji from his name and now everything is working as it should, except : 
`{"reqId":"e\/QbTdCBiJ8GRCdzTjt5","remoteAddr":"88.168.x.x","app":"PHP","message":"Undefined index: addressBookId at \/var\/www\/owncloud\/apps\/contacts\/lib\/hooks.php#109","level":3,"time":"2015-12-30T08:02:12+00:00"}`

**Comment by gvde** [comment]
The multiple versions is a problem.

I repeat: You may want to go through the other open (and recently closed) pull requests for some more fixes...

Seriously. The pull requests for the FN property splitting might already help. If none of those pull requests help you should post detailed information on the problem...

**Comment by CriticalNoob** [comment]
Sorry I wan't clear enough : the multiple version didn't prevent any import and didn't cause any problem to me.

I checked the open an recently closed pull requests and didn't find anything related to emojis.
I can't find the pull requests for the FN property splitting and I'm not sure how it might help.

I'm sorry I don't know how I could post more detailed informations, what do you want to know ?
This is a summary, if it can help :

If I import contacts from a .vcf file or sync contact using Apple Adressbook and one of the contact has an emoji in his name, the import will fail with the error given in previous messages, and the contact page of owncloud won't load.

The "fix" on my side is to clean my contact from any emoji.

I would gladly request a pull if I knew how to alter the code so that unsupported characters are not imported by owncloud, but I'm afraid that I don't have the competence to do so.

**Comment by CriticalNoob** [comment]
I tried the fix for multiple versions and nothing changed about emojis.

**Comment by gvde** [comment]
Please, please, please, READ what I write: I did not say that the multiple version prevents the import nor causes the previous issues. It does cause problems in certain circumstances and there is a fix for it. It has nothing to do with the emoji. I didn't say so.

I also wrote you should try pull request #1068 not #1067. #1067 is for stable 8.1, #1068 is for stable8.2. You supposedly have 8.2 that's why I have wrote #1068. Even if both are the same generally I would recommend to follow the advice given and not picking other pull requests, even if they have the same subject...

I also didn't write that there is a pull request about emojis (or at least not in regard to your problem). I suggested #1064 which deals with the splitting of the name and address properties. I don't say it will definitively fix your problem but it might depending on the encoding used...

You know the template. If the import fails there are error messages, log files, etc. The usual to find out what goes wrong. Attaching an unmodified vcf card which won't import to this issue may also be useful.

**Comment by CriticalNoob** [comment]
I'm sorry if I appear to be rude, but seriously I'm not sure about what I should do.

-If the multiple version wasn't the supposed source of my problem, as I stated that the emoji was the problem, how the multiple version fix should help me, or how I could help ? 
I would gladly report anything about this fix. 
I'm sorry I was confused and tried #1067 instead of #1068, I will do so, but what should I expect from it ?

-I don't see where you suggested #1064 but I will try it to see if it changes anything and report to the pull request if I see anything that can help.

-I gave all the error messages log files and unmodified vcf card in my las messages, do you want me to do a clean summary ?

**Comment by gvde** [comment]
1. You have posted a broken vcard which shows multiple VERSION and PRODID values. That is an issue fixed by #1068 and the master #1054. If you check the master pull requests #1054 you'll find links to the issue where it is referenced, some describe the issues which it fixes. There are various issues around this and it's a good idea to fix it if you come across it. That's why I have mentioned it. Because the card you have posted before is so badly broken...

2. #1067 and #1068 are identical. But in generally I recommend using the patch suggested which is for your version and not a different version. At occasion you may get into serious trouble if you apply a patch which is for a different version and not the correct backport...

3. I didn't suggest #1064 before I did.

4. I don't see the logs from when you import the broken card. You posted the logs after you have fixed the card. But not the logs which are created during importing the broken card.

5. You did not attach the unmodified card to your message but copied and pasted it into a web form, which was process by your web browser, the web server, backend server, again backend server, web server and my web browser to see it. There have been so many encodings and decodings in that whole process I would trust the result, even if it looks the same, for an issue which may be an encoding issue. It is impossible to tell if that, what my web browser presents me here is exactly the binary card from what you imported before. It might but again, for an issue which may be related to encoding, I don't trust it. Attach the card file to the message and it get's uploaded and hopefully stored in original binary form on the server where I can retrieve it.

**Comment by CriticalNoob** [comment]
1. Thanks, the fix seems to work and remove the multiple versions, although they were present only from a vcf import and not from a sync. Do you want me to report it is working to the pull request ?

2. I will be more cautious, thanks you.

3. You said "I suggested #1064" but I saw no reference to it in your previous message, that's why I was confused.

4. The log are in the first and second page.

5. My bad I'm uploading it.


[Nicolas  👾 -anon.zip](https://github.com/owncloud/contacts/files/74726/Nicolas.-anon.zip)

**Comment by CriticalNoob** [comment]
Ah and I found a better fix.

If I change the mysql columns from utf8 to utf8mb4 the problem disappear, so I guess the problem comes from an incompatibility between emojis and the current mysql structure.

**Comment by gvde** [comment]
Re 1.: yes it would be good if you would write in #1068 and #1054 (the pull request for the master branch) that the pull request removes the multiple property values from the imported card. (it's one part of what the pull requests fixes)

Re 4. The logs in the first and second posts are from "Import a moderately large contact list". It may contain the error related to the one broken card but it may also contains other log messages. For troubleshooting it's far easier  if you have a limited, focused set to look at. If you have identified one specific card to cause a problem than the logs for the import of that single card is of interest. Going through the logs of a 150 card import is a waste of time if it's easily possible to obtain a log which contains only the logs for the one broken card.

In other words:

The end of document error is related to the broken card which does not end in the END:VCARD tag.

The memory error may be related to the size of your import but is most likely not related to the broken card.

The logs int the first and second post show both. From the logs I can't tell which mesages is related with which problem. I can't tell whether you see the memory error even if you only try to import the single broken card instead of your large collection. 

So for troubleshooting, it's extremely important to focus the logs as good as possible to a single issue to get rid of any other issues/errors/message which may result in additional but unrelated logs. That's why I have asked for the specific logs which are created when you import the single broken card.

Re 5. Thanks. The emoji uses a four byte UTF-8 encoding. That requires a utf8mb4 in the database. I think I remember an issue regarding database storage and utf-8 in the owncloud core, but I am not sure. The database description in the contacts app just says "cblob" for the carddata column. So here doesn't look like the right place to fix this. I think, this needs to be handled in the core and how it creates the database there to make sure four bytes UTF-8 is generally stored correctly...

**Comment by CriticalNoob** [comment]
Okay thanks.
So here are my logs for a single card import of the "broken" card.

```
{"reqId":"gZ8XKVB3dW\/\/J7s41qaW","remoteAddr":"88.168.x.x","app":"contacts","message":"OCA\\Contacts\\Contact::retrieve Error parsing carddata  for: 6608 End of document reached prematurely","level":3,"time":"2015-12-30T10:31:46+00:00"}
{"reqId":"gZ8XKVB3dW\/\/J7s41qaW","remoteAddr":"88.168.x.x","app":"contacts","message":"OCA\\Contacts\\Contact::retrieve Error parsing carddata  for: 6608 End of document reached prematurely","level":3,"time":"2015-12-30T10:31:46+00:00"}
{"reqId":"gZ8XKVB3dW\/\/J7s41qaW","remoteAddr":"88.168.x.x","app":"contacts","message":"OCA\\Contacts\\Contact::retrieve Error parsing carddata  for: 6608 End of document reached prematurely","level":3,"time":"2015-12-30T10:31:46+00:00"}
{"reqId":"gZ8XKVB3dW\/\/J7s41qaW","remoteAddr":"88.168.x.x","app":"PHP","message":"Allowed memory size of 536870912 bytes exhausted (tried to allocate 323319062 bytes) at \/var\/www\/owncloud\/apps\/contacts\/lib\/utils\/jsonserializer.php#86","level":3,"time":"2015-12-30T10:31:56+00:00"}
{"reqId":"Ql8doWk5gyzLHp1yal7u","remoteAddr":"88.168.x.x","app":"carddav","message":"Exception: {\"Message\":\"End of document reached prematurely\",\"Exception\":\"Sabre\\\\VObject\\\\EofException\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(133): Sabre\\\\VObject\\\\Parser\\\\MimeDir->readLine()\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(63): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parseDocument()\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Reader.php(44): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parse('BEGIN:VCARD??VE...', 0)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CardDAV\\\/Plugin.php(894): Sabre\\\\VObject\\\\Reader::read('BEGIN:VCARD??VE...')\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CardDAV\\\/Plugin.php(328): Sabre\\\\CardDAV\\\\Plugin->convertVCard('BEGIN:VCARD??VE...', 'vcard3')\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CardDAV\\\/Plugin.php(255): Sabre\\\\CardDAV\\\\Plugin->addressbookMultiGetReport(Object(DOMDocument))\\n#6 [internal function]: Sabre\\\\CardDAV\\\\Plugin->report('{urn:ietf:param...', Object(DOMDocument), 'addressbooks\\\/fr...')\\n#7 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#8 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(710): Sabre\\\\Event\\\\EventEmitter->emit('report', Array)\\n#9 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpReport(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#10 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#11 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:REPORT', Array)\\n#12 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#13 \\\/var\\\/www\\\/owncloud\\\/apps\\\/contacts\\\/appinfo\\\/remote.php(84): Sabre\\\\DAV\\\\Server->exec()\\n#14 \\\/var\\\/www\\\/owncloud\\\/remote.php(137): require_once('\\\/var\\\/www\\\/ownclo...')\\n#15 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php\",\"Line\":250}","level":4,"time":"2015-12-30T10:34:02+00:00"}
```

And in apache2's logs :
```
[Wed Dec 30 11:31:56.290025 2015] [:error] [pid 1080] [client 88.168.x.x:62327] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 323319062 bytes) in /var/www/owncloud/apps/contacts/lib/utils/jsonserializer.php on line 86
```


I identified other problems with emoji, uploading a file with an emoji in its name work, but if you delete it you can't restore it, seems like a major incompatibility between emoji and the database. I'm going to fill an issue with core. 
Thanks for your help and sorry if I sometime sounded offensive.

**Comment by CriticalNoob** [comment]
Ok this is what I have found :

https://github.com/owncloud/core/pull/17978#issuecomment-126332406

Can't use owncloud with both mysql and emoji until devs decide to change that.
I'm gonna run some test to see if my cloud is viable with sqlite or postgresql.

**Comment by dzogrim** [comment]
I've the same problem here… with 3K contacts and I found I can't have any control on ""PHP","message":"Allowed memory size of 536870912 bytes exhausted" error no matter what I try to.
