### ISSUE TITLE
PHP errors feof() and fgets() after updating to v0.5.0.0

### ISSUE THREAD

**Issue by fcturner** [owncloud/contacts#1125]
As mentioned in #440, when "Dismissing" a reminder the following is shown within the data/owncloud.log on a oC 8.2.1 with contacts 0.5.0.0:

```
{"reqId":"lw5I5Za0gO01zqlsylBs","remoteAddr":"88.66.232.179","app":"PHP","message":"feof() expects parameter 1 to be resource, null given at \/var\/www\/owncloud\/3rdparty\/sabre\/vobject\/lib\/Parser\/MimeDir.php#245","level":3,"time":"2015-12-05T10:38:18+01:00"}
{"reqId":"lw5I5Za0gO01zqlsylBs","remoteAddr":"88.66.232.179","app":"PHP","message":"fgets() expects parameter 1 to be resource, null given at \/var\/www\/owncloud\/3rdparty\/sabre\/vobject\/lib\/Parser\/MimeDir.php#247","level":3,"time":"2015-12-05T10:38:18+01:00"}
{"reqId":"lw5I5Za0gO01zqlsylBs","remoteAddr":"88.66.232.179","app":"PHP","message":"feof() expects parameter 1 to be resource, null given at \/var\/www\/owncloud\/3rdparty\/sabre\/vobject\/lib\/Parser\/MimeDir.php#249","level":3,"time":"2015-12-05T10:38:18+01:00"}
{"reqId":"lw5I5Za0gO01zqlsylBs","remoteAddr":"88.66.232.179","app":"caldav","message":"Exception: {\"Message\":\"Error reading from input stream\",\"Exception\":\"Sabre\\\\VObject\\\\ParseException\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(102): Sabre\\\\VObject\\\\Parser\\\\MimeDir->readLine()\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(63): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parseDocument()\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Reader.php(44): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parse(NULL, 0)\\n#3 \\\/var\\\/www\\\/owncloud\\\/apps\\\/calendar\\\/lib\\\/object.php(249): Sabre\\\\VObject\\\\Reader::read(NULL)\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/calendar\\\/lib\\\/sabre\\\/backend.php(410): OC_Calendar_Object::editFromDAVData('contact_birthda...', 'local::7::124.i...', 'BEGIN:VCALENDAR...')\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/CalendarObject.php(104): OCA\\\\Calendar\\\\Sabre\\\\Backend->updateCalendarObject('contact_birthda...', 'local::7::124.i...', 'BEGIN:VCALENDAR...')\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1087): Sabre\\\\CalDAV\\\\CalendarObject->put('BEGIN:VCALENDAR...')\\n#7 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(501): Sabre\\\\DAV\\\\Server->updateFile('calendars\\\/Ranco...', Resource id #41, NULL)\\n#8 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#9 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#10 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#11 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#12 \\\/var\\\/www\\\/owncloud\\\/apps\\\/calendar\\\/appinfo\\\/remote.php(60): Sabre\\\\DAV\\\\Server->exec()\\n#13 \\\/var\\\/www\\\/owncloud\\\/remote.php(137): require_once('\\\/var\\\/www\\\/ownclo...')\\n#14 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php\",\"Line\":253}","level":4,"time":"2015-12-05T10:38:18+01:00"}
```

Which is about this piece of code in `owncloud/3rdparty/sabre/vobject/lib/Parser/MimeDir.php`:
```php
protected function readLine() {

    if (!is_null($this->lineBuffer)) {
        $rawLine = $this->lineBuffer;
        $this->lineBuffer = null;
    } else {
        do {
            $eof = feof($this->input);

            $rawLine = fgets($this->input);

            if ($eof || (feof($this->input) && $rawLine===false)) {
                throw new EofException('End of document reached prematurely');
            }
            if ($rawLine === false) {
                throw new ParseException('Error reading from input stream');
            }
            $rawLine = rtrim($rawLine, "\r\n");
        } while ($rawLine === ''); // Skipping empty lines
        $this->lineIndex++;
    }
```
A possible solution might be to replace the...
```php
} else {
```
...to...
```php
} elseif (!is_null($this->input)) {
```
...but I don't know if this will break something else.

**Comment by cwr10010** [comment]
Got that too and the above suggestion is a quick shot that does not help but break the flow handling (rawLine will not be initialized) Any help appreciated!

**Comment by M0ses** [comment]
looks like the same problem here

```
{"reqId":"0LYdRQ+a4DY9thD7GiO0","remoteAddr":"<protected-ip>","app":"PHP","message":"feof() expects parameter 1 to be resource, null given at \/var\/www\/owncloud\/3rdparty\/sabre\/vobject\/lib\/Parser\/MimeDir.php#245","level":3,"time":"2016-02-10T07:58:45+00:00"}
{"reqId":"0LYdRQ+a4DY9thD7GiO0","remoteAddr":"<protected-ip>","app":"PHP","message":"fgets() expects parameter 1 to be resource, null given at \/var\/www\/owncloud\/3rdparty\/sabre\/vobject\/lib\/Parser\/MimeDir.php#247","level":3,"time":"2016-02-10T07:58:46+00:00"}
{"reqId":"0LYdRQ+a4DY9thD7GiO0","remoteAddr":"<protected-ip>","app":"PHP","message":"feof() expects parameter 1 to be resource, null given at \/var\/www\/owncloud\/3rdparty\/sabre\/vobject\/lib\/Parser\/MimeDir.php#249","level":3,"time":"2016-02-10T07:58:46+00:00"}
{"reqId":"0LYdRQ+a4DY9thD7GiO0","remoteAddr":"<protected-ip>","app":"carddav","message":"Exception: {\"Message\":\"Error reading from input stream\",\"Exception\":\"Sabre\\\\VObject\\\\ParseException\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(102): Sabre\\\\VObject\\\\Parser\\\\MimeDir->readLine()\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(63): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parseDocument()\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Reader.php(44): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parse(NULL, 0)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CardDAV\\\/Plugin.php(555): Sabre\\\\VObject\\\\Reader::read(NULL)\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CardDAV\\\/Plugin.php(500): Sabre\\\\CardDAV\\\\Plugin->validateFilters(NULL, Array, 'anyof')\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CardDAV\\\/Plugin.php(259): Sabre\\\\CardDAV\\\\Plugin->addressbookQueryReport(Object(DOMDocument))\\n#6 [internal function]: Sabre\\\\CardDAV\\\\Plugin->report('{urn:ietf:param...', Object(DOMDocument), 'addressbooks\\\/fr...')\\n#7 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#8 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(710): Sabre\\\\Event\\\\EventEmitter->emit('report', Array)\\n#9 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpReport(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#10 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#11 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:REPORT', Array)\\n#12 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#13 \\\/var\\\/www\\\/owncloud\\\/apps\\\/contacts\\\/appinfo\\\/remote.php(84): Sabre\\\\DAV\\\\Server->exec()\\n#14 \\\/var\\\/www\\\/owncloud\\\/remote.php(137): require_once('\\\/var\\\/www\\\/ownclo...')\\n#15 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php\",\"Line\":253}","level":4,"time":"2016-02-10T07:58:46+00:00"}

```

This appears in the access log:

```
<protected-ip> - <protected-user> [10/Feb/2016:09:04:11 +0100] "PROPFIND /owncloud/remote.php/carddav/addressbooks/<protected-user>/kontakte/ HTTP/1.1" 207 1995 "-" "DAVdroid/0.9.1.3 (2016/01/03; dav4android) Android/5.0"
<protected-ip> - <protected-user> [10/Feb/2016:09:04:12 +0100] "REPORT /owncloud/remote.php/carddav/addressbooks/<protected-user>/kontakte/ HTTP/1.1" 500 940 "-" "DAVdroid/0.9.1.3 (2016/01/03; dav4android) Android/5.0"
<protected-ip> - <protected-user> [10/Feb/2016:09:04:12 +0100] "PROPFIND /owncloud/remote.php/carddav/addressbooks/<protected-user>/kontakte/ HTTP/1.1" 207 62804 "-" "DAVdroid/0.9.1.3 (2016/01/03; dav4android) Android/5.0"
<protected-ip> - <protected-user> [10/Feb/2016:09:04:13 +0100] "REPORT /owncloud/remote.php/carddav/addressbooks/<protected-user>/kontakte/ HTTP/1.1" 404 947 "-" "DAVdroid/0.9.1.3 (2016/01/03; dav4android) Android/5.0"
```
might have to do something with the data sets in my addressbook. other accounts can syncronize contacts (but missing shared calender). Exporting addressbook and reimporting did not help.

**Comment by cwr10010** [comment]
For me it worked to disconnect and reconnect Calendar.app to the account. Btw I have shared calendars, but no shared addressbooks.

**Comment by M0ses** [comment]
Sorry for bothering you (but at least my Problem is now documented for others :-) )

Finally I found out, where the Problem was. Some of my addressbook entries had URL in the UID field, which completly broke sync with davdroid. I exported to VCF, cleaned the broken entries and reimported. Now it works.

**Comment by fcturner** [comment]
> @cwr10010 commented 12 days ago
Got that too and the above suggestion is a quick shot that does not help but break the flow handling (rawLine will not be initialized) Any help appreciated!

Well, I thought that it *shouldn't* be initialized, since the error only happens when `$rawLine` is false:
```php
$rawLine = fgets($this->input);
~
if ($rawLine === false) {
	throw new ParseException('Error reading from input stream');
}
```
But you're right, my suggestion only keeps the log clean :)
From this code and the code I posted earlier, one must ask himself why `$this->lineBuffer` and `fgets($this->input)` are both NULL. I don't know :(
