### ISSUE TITLE
Invalid Mimedir file. Line starting at 14 did not follow iCalendar vCard conventions

### ISSUE THREAD

**Issue by sndrsk** [owncloud/contacts#1130]
Yesterday I set up a new iPhone and synced it with my Contacts on oC via CardDAV. Everything went great. This morning I noticed there was (at least) one contact that didn't sync. It was a newer contact, so I waited. After a few hours it didn't show up. I tried disabling the CardDAV account on the iPhone and re-enabled it and then all of the contacts went away. I have tried completely removing the CardDAV account on the iPhone and re-adding it with no success, it's still not syncing.

In the logs I get this:
```
Exception: {"Message":"Invalid Mimedir file. Line starting at 14 did not follow iCalendar\/vCard conventions","Exception":"Sabre\\VObject\\ParseException","Code":0,"Trace":"#0 \/home\/user\/domain\/box\/3rdparty\/sabre\/vobject\/lib\/Parser\/MimeDir.php(189): Sabre\\VObject\\Parser\\MimeDir->readProperty(';UNKNOWN=\"GROUP...')\n#1 \/home\/user\/domain\/box\/3rdparty\/sabre\/vobject\/lib\/Parser\/MimeDir.php(137): Sabre\\VObject\\Parser\\MimeDir->parseLine(';UNKNOWN=\"GROUP...')\n#2 \/home\/user\/domain\/box\/3rdparty\/sabre\/vobject\/lib\/Parser\/MimeDir.php(63): Sabre\\VObject\\Parser\\MimeDir->parseDocument()\n#3 \/home\/user\/domain\/box\/3rdparty\/sabre\/vobject\/lib\/Reader.php(44): Sabre\\VObject\\Parser\\MimeDir->parse('BEGIN:VCARD\\r\\nVE...', 0)\n#4 \/home\/user\/domain\/box\/3rdparty\/sabre\/dav\/lib\/CardDAV\/Plugin.php(894): Sabre\\VObject\\Reader::read('BEGIN:VCARD\\r\\nVE...')\n#5 \/home\/user\/domain\/box\/3rdparty\/sabre\/dav\/lib\/CardDAV\/Plugin.php(328): Sabre\\CardDAV\\Plugin->convertVCard('BEGIN:VCARD\\r\\nVE...', 'vcard3')\n#6 \/home\/user\/domain\/box\/3rdparty\/sabre\/dav\/lib\/CardDAV\/Plugin.php(255): Sabre\\CardDAV\\Plugin->addressbookMultiGetReport(Object(DOMDocument))\n#7 [internal function]: Sabre\\CardDAV\\Plugin->report('{urn:ietf:param...', Object(DOMDocument), 'addressbooks\/ke...')\n#8 \/home\/user\/domain\/box\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#9 \/home\/user\/domain\/box\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(710): Sabre\\Event\\EventEmitter->emit('report', Array)\n#10 [internal function]: Sabre\\DAV\\CorePlugin->httpReport(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#11 \/home\/user\/domain\/box\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#12 \/home\/user\/domain\/box\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:REPORT', Array)\n#13 \/home\/user\/domain\/box\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#14 \/home\/user\/domain\/box\/apps\/contacts\/appinfo\/remote.php(84): Sabre\\DAV\\Server->exec()\n#15 \/home\/user\/domain\/box\/remote.php(137): require_once('\/home\/user...')\n#16 {main}","File":"\/home\/user\/domain\/box\/3rdparty\/sabre\/vobject\/lib\/Parser\/MimeDir.php","Line":385} 
```

I might assume I have a bad contact in there somewhere in my address book but I don't see it in the vcf file. Any suggestions?

### Server configuration
**Operating system**: Linux

**Web server:** Debian

**Database:** MySQL

**PHP version:** 5.4

**ownCloud version:** (see ownCloud admin page) 8.2

**Comment by sndrsk** [comment]
Disregard, it looks like this is a Calendar issue and I need coffee. Closing.

**Comment by sndrsk** [comment]
Wait, no, the errors say it's CardDAV. Any ideas? Other issues I'm reviewing points to a bad calendar entry but the errors are making references to CardDAV.

**Comment by gvde** [comment]
One of your cards seems to contain something with ";UNKNOWN="GROUP". That looks pretty broken to me...

**Comment by sndrsk** [comment]
There were some cards with some groups left in the notes, I removed those, but I still had the same issue. I exported the contacts, deleted them in oC, then imported them to Gmail, then exported them from Gmail, and imported them to oC and they seem to be working now. Closing.
