### ISSUE TITLE
bug : import of contact not working

### ISSUE THREAD

**Issue by DoumeDuSud** [owncloud/contacts#333]
### Steps to reproduce
1. I try to import a contact file in .csv provide from google contact also a .cvf file)
2. nothing happen, no importation
### Expected behaviour

The importation of my contact
### Actual behaviour

nothing

I don't know if it's in relation with this #313 
### Server configuration

**Operating system**:
ubuntu server 15.4
**Web server:**
apache 2
**Database:**
maria DB
**PHP version:**
php5
**ownCloud version:** (see ownCloud admin page)
9.0.0 stable
**Contacts version:** (see ownCloud apps page)
1.1.0.0
**Updated from an older ownCloud or fresh install:**
fresh
**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

No errors have been found.

**List of activated apps:**

```
/var/www/owncloud# sudo -u www-data php occ app:list
Enabled:
  - activity: 2.2.1
  - calendar: 1.0
  - comments: 0.2
  - contacts: 1.1.0.0
  - conversations: 0.2.3
  - dav: 0.1.5
  - direct_menu: 0.7.1
  - documents: 0.12.0
  - encryption: 1.2.0
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - gpxpod: 0.9.16
  - notifications: 0.2.3
  - ownbackup: 0.3.8
  - ownnote: 1.07
  - passwords: 17.2
  - provisioning_api: 0.4.1
  - rainloop: 4.12
  - sketch: 0.1.2
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - external
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
    "system": {
        "updatechecker": false,
        "instanceid": "ocs6mg77usdq",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "bureau.ds-guiraud.fr"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/bureau.ds-guiraud.fr\/owncloud",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "nuagebd2",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "appstore.experimental.enabled": true

```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** no but acces in https

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
#### LDAP configuration (delete this part if not used)

```
  [Symfony\Component\Console\Exception\CommandNotFoundException]  
  There are no commands defined in the "ldap" namespace. 
```
### Client configuration

**Browser:**
firefox & chrome
**Operating system:**
ubuntu & windows 10
**CardDAV-clients:**
#### Web server error log

```
Insert your webserver log here
```
#### ownCloud log (data/owncloud.log)

```
Fatal   webdav  Exception: {"Message":"HTTP\/1.1 405 The resource you tried to create already exists","Exception":"Sabre\\DAV\\Exception\\MethodNotAllowed","Code":0,"Trace":"#0 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(590): Sabre\\DAV\\Server->createCollection('addressbooks\/us...', Object(Sabre\\DAV\\MkCol))\n#1 [internal function]: Sabre\\DAV\\CorePlugin->httpMkcol(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#2 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#3 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(459): Sabre\\Event\\EventEmitter->emit('method:MKCOL', Array)\n#4 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#5 \/var\/www\/owncloud\/apps\/dav\/lib\/server.php(137): Sabre\\DAV\\Server->exec()\n#6 \/var\/www\/owncloud\/apps\/dav\/appinfo\/v2\/remote.php(29): OCA\\DAV\\Server->exec()\n#7 \/var\/www\/owncloud\/remote.php(138): require_once('\/var\/www\/ownclo...')\n#8 {main}","File":"\/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","Line":1121,"User":"admin"}    2016-04-02T18:43:55+00:00
```
#### Browser log

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by DarkSteve** [comment]
Sounds related to issue [https://github.com/owncloud/contacts/issues/291]. Hopefully this will be fixed soon, it's a major pain in my rectum.

**Comment by DoumeDuSud** [comment]
Yes @DarkSteve it's the same, sorry I don't see that issue

Thanks for all working on it :-)
