### ISSUE TITLE
Old contacts are not showing up after upgrading to ownCloud 9.0.1 and Contacts 1.2.0.0

### ISSUE THREAD

**Issue by pbek** [owncloud/contacts#389]
As requested by @DeepDiver1975 in https://github.com/owncloud/contacts/pull/374:
I had several hundred contacts before the upgrade to ownCloud 9.0.1 and Contacts 1.2.0.0. After the upgrade they don't show up at the contact page.

Syncing via Dav still works.
If I create a new contact on the web interface in my old address book `Contacts` it doesn't show up on the web interface neither.
Although it is available via Dav.

Then I created a new address book `Test` on the web-interface. I could add a new contact there and it showed up on the web-interface.
### Expected behaviour

My old contacts load.
### Actual behaviour

They don't load.
### Server configuration

**Operating system**:
Debian 7.10

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.6.20

**ownCloud version:**
9.0.1

**Contacts version:**
1.2.0.0

**Updated from an older ownCloud or fresh install:**
Update from 8.x

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - bookmarks: 0.8
  - calendar: 1.1
  - comments: 0.2
  - contacts: 1.2.0.0
  - dav: 0.1.6
  - external: 1.2
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - news: 8.7.1
  - notes: 2.0.1
  - notifications: 0.2.3
  - ownbackup: 0.3.8
  - provisioning_api: 0.4.1
  - qownnotesapi: 0.4.3
  - systemtags: 0.2
  - tasks: 0.9.0
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - user_external
  - user_ldap
```

**config.php:**

```
$CONFIG = array (
  'instanceid' => 'XXXX',
  'passwordsalt' => 'XXXX',
  'trusted_domains' => 
  array (
    0 => 'XXX.XXX.XXXX',
  ),
  'datadirectory' => '/XXXX/data',
  'dbtype' => 'mysql',
  'version' => '9.0.1.3',
  'dbname' => 'XXXX',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => 'XXX',
  'installed' => true,
  'forcessl' => true,
  'mail_from_address' => 'XXX',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'XXXX',
  'theme' => '',
  'maintenance' => false,
  'secret' => 'XXXX',
  'appstoreenabled' => true,
  'appstoreurl' => 'https://api.owncloud.com/v1',
  'appstore.experimental.enabled' => true,
  'loglevel' => 2,
  'trashbin_retention_obligation' => 'auto',
  'updatechecker' => false,
);
```

**Are you using external storage, if yes which one:** 
no

**Are you using encryption:**
no
### Client configuration

**Browser:**
Google Chrome Version 50.0.2661.86 (64-bit)

**Operating system:**
KDE Neon 16.04
#### Web server error log

nothing in the error.log, this from the access log (I removed the requests for assets):

```
178.191.x.x - - [25/Apr/2016:07:36:13 +0200] "PROPFIND /remote.php/dav/addressbooks HTTP/1.1" 207 1699 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.86 Safari/537.36"
178.191.x.x - - [25/Apr/2016:07:36:13 +0200] "PROPFIND /remote.php/dav/principals/users/patrizio/ HTTP/1.1" 207 1716 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.86 Safari/537.36"
178.191.x.x - - [25/Apr/2016:07:36:13 +0200] "PROPFIND /remote.php/dav/addressbooks/users/patrizio/ HTTP/1.1" 207 2984 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.86 Safari/537.36"
178.191.x.x - - [25/Apr/2016:07:36:13 +0200] "PROPFIND /remote.php/dav/addressbooks/users/patrizio/Test/ HTTP/1.1" 207 3528 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.86 Safari/537.36"
178.191.x.x - - [25/Apr/2016:07:36:13 +0200] "PROPFIND /remote.php/dav/addressbooks/users/patrizio/contacts/ HTTP/1.1" 207 586982 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.86 Safari/537.36"
178.191.x.x - - [25/Apr/2016:07:36:15 +0200] "PROPFIND /remote.php/dav/addressbooks/users/patrizio/ HTTP/1.1" 207 1611 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.86 Safari/537.36"
178.191.x.x - - [25/Apr/2016:07:36:15 +0200] "REPORT /remote.php/dav/addressbooks/users/patrizio/Test/ HTTP/1.1" 207 1662 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.86 Safari/537.36"
178.191.x.x - - [25/Apr/2016:07:36:15 +0200] "PROPFIND /remote.php/dav/addressbooks/users/patrizio/ HTTP/1.1" 207 1611 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.86 Safari/537.36"
178.191.x.x - - [25/Apr/2016:07:36:15 +0200] "REPORT /remote.php/dav/addressbooks/users/patrizio/contacts/ HTTP/1.1" 207 10115263 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.86 Safari/537.36"
```
#### ownCloud log (data/owncloud.log)

no log entries were added by the call to show all contacts
#### Browser log

just a `Failed to parse SourceMap`

**Comment by dvinz** [comment]
Hi All,

Same problem for me.

## Server configuration

### Operating system:

PRETTY_NAME="Debian GNU/Linux 8 (jessie)"

### Web server:

Nginx

### Database:

MySQL

### PHP version:

PHP 5.6.19-0+deb8u1

### ownCloud version:

9.0.1

### Contacts version:

1.2.0.0

### Owncloud log tell  Fatal error webdav :

```
Exception: {"Message":"Invalid Mimedir file. Line starting at 4 did not follow iCalendar\/vCard conventions","Exception":"Sabre\\VObject\\ParseException","Code":0,"Trace":"#0 \/var\/www\/owncloud\/3rdparty\/sabre\/vobject\/lib\/Parser\/MimeDir.php(189): Sabre\\VObject\\Parser\\MimeDir->readProperty(';=\"IM: AIM: 445...')\n#1 \/var\/www\/owncloud\/3rdparty\/sabre\/vobject\/lib\/Parser\/MimeDir.php(137): Sabre\\VObject\\Parser\\MimeDir->parseLine(';=\"IM: AIM: 445...')\n#2 \/var\/www\/owncloud\/3rdparty\/sabre\/vobject\/lib\/Parser\/MimeDir.php(63): Sabre\\VObject\\Parser\\MimeDir->parseDocument()\n#3 \/var\/www\/owncloud\/3rdparty\/sabre\/vobject\/lib\/Reader.php(44): Sabre\\VObject\\Parser\\MimeDir->parse('BEGIN:VCARD\\r\\nVE...', 0)\n#4 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/CardDAV\/Plugin.php(477): Sabre\\VObject\\Reader::read('BEGIN:VCARD\\r\\nVE...')\n#5 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/CardDAV\/Plugin.php(422): Sabre\\CardDAV\\Plugin->validateFilters('BEGIN:VCARD\\r\\nVE...', Array, 'anyof')\n#6 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/CardDAV\/Plugin.php(202): Sabre\\CardDAV\\Plugin->addressbookQueryReport(Object(Sabre\\CardDAV\\Xml\\Request\\AddressBookQueryReport))\n#7 [internal function]: Sabre\\CardDAV\\Plugin->report('{urn:ietf:param...', Object(Sabre\\CardDAV\\Xml\\Request\\AddressBookQueryReport), 'addressbooks\/us...')\n#8 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#9 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(716): Sabre\\Event\\EventEmitter->emit('report', Array)\n#10 [internal function]: Sabre\\DAV\\CorePlugin->httpReport(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#11 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#12 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(459): Sabre\\Event\\EventEmitter->emit('method:REPORT', Array)\n#13 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#14 \/var\/www\/owncloud\/apps\/dav\/lib\/server.php(142): Sabre\\DAV\\Server->exec()\n#15 \/var\/www\/owncloud\/apps\/dav\/appinfo\/v2\/remote.php(29): OCA\\DAV\\Server->exec()\n#16 \/var\/www\/owncloud\/remote.php(138): require_once('\/var\/www\/ownclo...')\n#17 {main}","File":"\/var\/www\/owncloud\/3rdparty\/sabre\/vobject\/lib\/Parser\/MimeDir.php","Line":385,"User":"toto"}
```

Best regards

**Comment by DeepDiver1975** [comment]
@dvinz you have an invalid vcard in your database - please try to fix it or delete the card from the database

**Comment by dvinz** [comment]
@DeepDiver1975 Tanks,

How identify them ?

**Comment by DeepDiver1975** [comment]
> readProperty(';=\"IM: AIM: 445...')

this is where is break - run a query like (pseudo code - you might need to adopt this to work properly on mysql):

``` sql
select * from oc_cards where carddata like '%AIM: 445%'
```

**Comment by qwc** [comment]
EDIT: I was able to solve my problem through a backup after my wife confessed to me that she had done something on our tablet thinking she was editing her account, but was doing that on my tablet account...

**Comment by Wikinaut** [comment]
Same problem here. No contacts are listed anymore  :-((
Contact App spinner is not cleared. Empty list.
- PHP version: PHP 7.0.5 
- ownCloud version: 9.0.1
- Contacts version: 1.2.0.0

@DeepDiver1975 
I do not have query results like `select * from oc_cards where carddata like '%AIM: 445%'`

**Comment by DeepDiver1975** [comment]
> I do not have query results like select \* from oc_cards where carddata like '%AIM: 445%'

@Wikinaut of course not - AIM: 445 is specific for @dvinz to identify the broken card on his installation.

**Comment by Wikinaut** [comment]
@DeepDiver1975 
that's clear.

However, how can I (help to) locate the problem in the app, or in the contact database ?

**Comment by dvinz** [comment]
Hi all,

I clear all broken card and it work.
Thanks for you help

DVinz

**Comment by Wikinaut** [comment]
@dvinz 
But your solution is not a general solution. What do you mean by "broken" ? Why is the present OC version 9.0.1 not able to repair potentially broken cards, whereas the previous versions could do this.

**Comment by Wikinaut** [comment]
I suggest, that app developers add some code to make the app more robust.

**Comment by Wikinaut** [comment]
@DeepDiver1975 I am willing to help, but I do not know where to start - there are no php errors in the log file.

**Comment by Wikinaut** [comment]
Perhaps a javascript issue ?

**Comment by dvinz** [comment]
@Wikinaut I delete all vcard was povoc error (see your owncloud log to identify them) from my oc_cards DB. In my case, think some vcard attribute are not recognize bye new contacts apps.

**Comment by Wikinaut** [comment]
@dvinz an my approach to software is to write what I call "self-healing software", I mean, to make software (here: the contact app) so robust, that it can cope with (some common) irregularities. perhaps I can help here later.

Can you tell me, what kind of irregularities your contact database had, apart from the reported problem ?

**Comment by conan0276** [comment]
Sorry guys this does not work for me either. My owncloud log does not show anything all contacts are gone in the web-ui and I get sync errors...

**Comment by bitsandnumbers** [comment]
Upon upgrading from 8.2.5 to 9.0.2 I have the same issue as above : no contact load in the contact app. All my contacts are gone. No log about this issue. The spinning wheel spin forever. I have not checked if sync is working (I hope it is though).

On a side note, I had to put asset pipeline to off for the calendar app to work. It's a lot of issues for a new release ^^

EDIT: I get a 504 Gateway error when trying to download my contacts from the settings panel in the bottom left corner of the contacts app.

EDIT 2 : I do get a log after digging : 

`{"reqId":"Nec9h1OUuYBNdXvYfZ7w","remoteAddr":"192.168.1.14","app":"carddav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/usr\\\/local\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/usr\\\/local\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/usr\\\/local\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/usr\\\/local\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/carddav.php(75): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/usr\\\/local\\\/www\\\/owncloud\\\/remote.php(138): require_once('\\\/usr\\\/local\\\/www\\\/...')\\n#6 {main}\",\"File\":\"\\\/usr\\\/local\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":188,\"User\":false}","level":0,"time":"2016-05-16T17:29:44+00:00","method":"PROPFIND","url":"\/remote.php\/carddav\/addressbooks\/USERNAME\/contacts\/","user":"--"}`

**Comment by MartinProefrock** [comment]
I had same issue as above:
Same problem here. No contacts are listed anymore :-((
Contact App spinner is not cleared. Empty list.

Tracked it down to entries with the "note" field having too much content
- Add the "note" field
- Enter some long text (> 100 chars?)
  Entry is saved without any warning
  OR
- Create an entry with a long "note" field on a client (e.g. thunderbird) and sync it 

Re-opening "contacts" app: nothing is shown any more

Syncing to e.g. thunderbird works, the long content shows up there
When truncating the "note" field in thunderbird addressbook and re-syncing, the contact app shows the list on next try

I do not know the reason, but the symptom is that in file
apps/contacts/js/dav/dav.js
"function childNodes(node)"
node is undefined, which causes a JS error

Adding an "if (! node) { return "new Array(); }" causes the wait cursor to stop, but still no entries are shown

**Comment by pbek** [comment]
are there any news on this issue, @DeepDiver1975?

**Comment by pbek** [comment]
I just updated to Contacts 1.3.0.0. Now there are no error messages and spinner any more, but the contacts from my old address book still will not show up. There are no significant javascript errors. Accessing them via carddav is still working, as is exporting the address book in Contacts.

**Comment by ckujau** [comment]
I ran into this as well, but I happened sometime after upgrading from OC 9.0.1-1.1 to 9.0.1-3.1 or 9.0.2-1.1 (on Debian/Jessie). After that, a new table `oc_cards` was created but carried only about half the contacts from `oc_contacts_cards`. Unfortunately, I only noticed this some weeks later that "some" contacts are missing. I tried to [convert](https://gist.github.com/ckujau/779f9d4f77353b9cd367f95e2f46440c) the old contacts to the new `oc_cards` table, but then the Contacts app just shows a spinning wheel (`owncloud.log` has `"Invalid Mimedir file. Line starting at 7 did not follow iCalendar/vCard conventions` - btw, why is the logfile filled with so many backslashes? It's really hard to read.).

At this point I see no other solution than to downgrade to v8 again, use a backup copy of `owncloud.db` (Sqlite) with all contacts still in `oc_contacts_cards` and try to export my contacts. Then upgrade to v9 and import the contacts again. Are there any other options?

Note: I have run into [#22959](https://github.com/owncloud/core/issues/22959), so this may have contributed to that b0rkage.

<pre>
$ echo "select count(*) from oc_contacts_cards; select count(*) from oc_cards;" | sqlite3 data/owncloud.db
144 66
</pre>

**Comment by mhzawadi** [comment]
I too get this issue, I have contacts that get synced from my HTC and have lots of notes.

# 

Request headers:

Request URL:https://owncloud.horwood.biz/remote.php/dav/addressbooks/users/matt/contacts/
Request Method:REPORT
Status Code:504 Gateway Time-out
Remote Address:192.168.49.200:443
Response Headers
view source
Connection:keep-alive
Content-Length:578
Content-Type:text/html
Date:Mon, 01 Aug 2016 20:40:42 GMT
Server:nginx
Request Headers
view source
Accept:_/_
Accept-Encoding:gzip, deflate, lzma, sdch, br
Accept-Language:en-GB,en-US;q=0.8,en;q=0.6
Connection:keep-alive
Content-Length:575
Content-Type:application/xml;charset=UTF-8
Cookie:
Depth:1
Host:owncloud.horwood.biz
Origin:https://owncloud.horwood.biz
requesttoken:
User-Agent:Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36 OPR/38.0.2220.41
Request Payload
<card:addressbook-query xmlns:card="urn:ietf:params:xml:ns:carddav"
                          xmlns:d="DAV:">
    <d:prop>
      <d:getetag />,<card:address-data />
    /d:prop
    
    card:filter
      <card:prop-filter name="FN">
      /card:prop-filter
    /card:filter
  /card:addressbook-query

# 

Console:

Failed to parse SourceMap: https://owncloud.horwood.biz/apps/contacts/js/vendor/angular-cache/dist/angular-cache.js.map
dav.js?v=21d48c2…:3640 REPORT https://owncloud.horwood.biz/remote.php/dav/addressbooks/users/matt/contacts/ 504 (Gateway Time-out)send @ dav.js?v=21d48c2…:3640callee$2$0$ @ dav.js?v=21d48c2…:3155tryCatch @ dav.js?v=21d48c2…:121invoke @ dav.js?v=21d48c2…:294Gp.(anonymous function) @ dav.js?v=21d48c2…:330onFulfilled @ dav.js?v=21d48c2…:5161(anonymous function) @ dav.js?v=21d48c2…:5150co @ dav.js?v=21d48c2…:5146send @ dav.js?v=21d48c2…:3133callee$0$0$ @ dav.js?v=21d48c2…:1763tryCatch @ dav.js?v=21d48c2…:121invoke @ dav.js?v=21d48c2…:294Gp.(anonymous function) @ dav.js?v=21d48c2…:330onFulfilled @ dav.js?v=21d48c2…:5161(anonymous function) @ dav.js?v=21d48c2…:5150co @ dav.js?v=21d48c2…:5146createPromise @ dav.js?v=21d48c2…:5126callee$0$0$ @ dav.js?v=21d48c2…:1929tryCatch @ dav.js?v=21d48c2…:121invoke @ dav.js?v=21d48c2…:294Gp.(anonymous function) @ dav.js?v=21d48c2…:330onFulfilled @ dav.js?v=21d48c2…:5161(anonymous function) @ dav.js?v=21d48c2…:5150co @ dav.js?v=21d48c2…:5146createPromise @ dav.js?v=21d48c2…:5126syncCollection @ dav.js?v=21d48c2…:3437syncAddressBook @ dav.js?v=21d48c2…:1832syncAddressBook @ dav.js?v=21d48c2…:1540sync @ addressBook_service.js:86(anonymous function) @ contact_service.js:33(anonymous function) @ contact_service.js:31
dav.js?v=21d48c2…:3648 Uncaught (in promise) Error: Bad status: 504(…)request.onreadystatechange @ dav.js?v=21d48c2…:3648
dav.js?v=21d48c2…:3648 Uncaught (in promise) Error: Bad status: 504(…)

**Comment by irgendwie** [comment]
#502 fixes the endless spinner if username contains spaces. Broken vcards can still lead to the mentioned issue!

**Comment by bitsandnumbers** [comment]
I've got the same issue (i.e: spinning wheel in contacts list) and a "gateway timeout" error when trying to download the vcard. No errors in logs (even while in level 0). My contacts app is the latest to date, straight from the repo v1.4 (so using the patch mentioned above)  running on OC 9.1. I have no spaces in my username.

Any news on this issue ?

As a side note, I had this same issue with OC 9.0.2, but can"t remember if I fixed it before upgrading to 9.1. I mostly use the dav sync to have contacts show up in 3rd party apps.

**Comment by pbek** [comment]
I exported all my contacts, delete them and imported them back. That worked for two hours. I could browse all my contacts (after importing half of them again because they weren't imported the first time)... But later suddenly I got the dreaded spinner again and my contacts were gone from the  web-browser. They were still available via CardDAV, like before. No error messages in the ownCloud log files... I tried Nextcloud and had the same issue.

Currently I'm on Nextcloud 10 and Contacts 1.4.

**Comment by Wikinaut** [comment]
Problem went away after I upgraded/migrated from ownCloud 9.0.x to Nextcloud 10.0.1.

**Comment by pbek** [comment]
Neither migrating to NC nor exporting/importing all contacts helped in my case...

**Comment by DeepDiver1975** [comment]
It's still hard to get an understanding of the issue you are facing @pbek - most probably the issue is within parsing the vcard on the client side within the app.

**Comment by pbek** [comment]
@DeepDiver1975 I can access them with all kind of 3rd party apps, like iOS / OS X Contacts, KAddressbook, ...

**Comment by DeepDiver1975** [comment]
> I can access them with all kind of 3rd party apps, like iOS / OS X Contacts, KAddressbook, ...

most probably because they are more flexible with respect to 'invalid' vcards

**Comment by pbek** [comment]
I would love to know which one are invalid, but there are no log nor javascript errors... It just says "no contacts" after a while. The curious thing is that I saw my contacts for about 10min in the beginning... 

It would help a lot if contacts would throw some errors/warning if there are parsing problems...

**Comment by DeepDiver1975** [comment]
The problem is within the 3rdparty libs we use. They just die and give no errors

**Comment by IwishIcanFLighT** [comment]
I just upgraded my OC server to 9.1.2 and Calendar to 1.4 and noticed that both my calendar and contacts pages are broken.
The contacts page (1.4.0.0) loads a blank empty page like @pbek.
However the logs are empty, the sync still works fine with my android and looking at my database everything is still here. Any update on that issue?

**Comment by pbek** [comment]
@IwishIcanFLighT do you maybe have this issue: https://github.com/nextcloud/server/issues/3740

**Comment by deisi** [comment]
are there any updates on this matter? Its really a killing bug.

**Comment by pbek** [comment]
@deisi, does my last comment at <https://github.com/nextcloud/server/issues/3740> help you? That was what I did as workaround...

**Comment by deisi** [comment]
you meaning splitting up the adressbooks into smaller chunks. Didnt try yet but will. Thx

**Comment by pbek** [comment]
yes, I did that...

**Comment by bitsandnumbers** [comment]
Issue solved with nextcloud 11.0.3 on my end

**Comment by Wikinaut** [comment]
I moved to Nextcloud, and everything works fine now.
