### ISSUE TITLE
Not saving entered info?

### ISSUE THREAD

**Issue by 0-kaladin** [owncloud/contacts#565]
### Steps to reproduce
I'm using the contact app on OC9.1.2 Stable and everything is working fine as far as the contacts sync'ing down to carddav clients. My issue is when i make any changes they don't always get saved. For example if i update a users phone number I'd enter +1 555 123 4567
I can click away from the user and come back and the number is there. but if i sync my client i might just see the number as +1 55
like the rest didn't get saved. if i refresh my browser the contact shows the +1 55 and I have to enter the rest of the number again.
I generally have to enter things like 3 times before it all saves.
Is this something to do with server cache maybe? should I disable that and try? Using chrome or IE it does this. haven't tried other browsers.

### Expected behaviour
Enter info once, it stays saved.

### Actual behaviour
Pieces of entered info get cut off.   refresh, have to re-enter. rinse. repeat

### Server configuration
**Operating system**:
Debian Jessie 8

**Web server:**
nginx

**Database:**
mariadb

**PHP version:**
PHP 7.0.14-1~dotdeb+8.1 (cli) ( NTS )

**ownCloud version:** (see ownCloud admin page)
9.1.3 (stable)

**Contacts version:** (see ownCloud apps page)
1.5.1

**Updated from an older ownCloud or fresh install:**
fresh install

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

**CardDAV-clients:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```
`Error while running background job (class: OC\Migration\BackgroundRepair, arguments: Array ( [app] => dav [step] => OCA\DAV\Migration\GenerateBirthdays ) ): {"Exception":"OC\\ServerNotAvailableException","Message":"Lost connection to LDAP server.","Code":0,"Trace":"#0 \/var\/www\/owncloud\/apps\/user_ldap\/lib\/LDAP.php(257): OCA\\User_LDAP\\LDAP->postFunctionCall()\n#1 \/var\/www\/owncloud\/apps\/user_ldap\/lib\/LDAP.php(178): OCA\\User_LDAP\\LDAP->invokeLDAPMethod('read', Resource id #65, 'cn=ppaul,ou=kir...', 'objectClass=*', Array)\n#2 \/var\/www\/owncloud\/apps\/user_ldap\/lib\/Access.php(175): OCA\\User_LDAP\\LDAP->read(Resource id #65, 'cn=ppaul,ou=kir...', 'objectClass=*', Array)\n#3 \/var\/www\/owncloud\/apps\/user_ldap\/lib\/Group_LDAP.php(314): OCA\\User_LDAP\\Access->readAttribute('cn=ppaul,ou=kir...', 'primaryGroupID')\n#4 \/var\/www\/owncloud\/apps\/user_ldap\/lib\/Group_LDAP.php(338): OCA\\User_LDAP\\Group_LDAP->getEntryGroupID('cn=ppaul,ou=kir...', 'primaryGroupID')\n#5 \/var\/www\/owncloud\/apps\/user_ldap\/lib\/Group_LDAP.php(421): OCA\\User_LDAP\\Group_LDAP->getUserPrimaryGroupIDs('cn=ppaul,ou=kir...')\n#6 \/var\/www\/owncloud\/apps\/user_ldap\/lib\/Group_LDAP.php(458): OCA\\User_LDAP\\Group_LDAP->getUserPrimaryGroup('cn=ppaul,ou=kir...')\n#7 \/var\/www\/owncloud\/lib\/private\/Group\/Manager.php(245): OCA\\User_LDAP\\Group_LDAP->getUserGroups('ppaul')\n#8 \/var\/www\/owncloud\/lib\/private\/Group\/Manager.php(232): OC\\Group\\Manager->getUserIdGroups('ppaul')\n#9 \/var\/www\/owncloud\/apps\/dav\/lib\/Connector\/Sabre\/Principal.php(149): OC\\Group\\Manager->getUserGroups(Object(OC\\User\\User))\n#10 \/var\/www\/owncloud\/apps\/dav\/lib\/CardDAV\/CardDavBackend.php(127): OCA\\DAV\\Connector\\Sabre\\Principal->getGroupMembership('principals\/user...', true)\n#11 \/var\/www\/owncloud\/apps\/dav\/lib\/CalDAV\/BirthdayService.php(180): OCA\\DAV\\CardDAV\\CardDavBackend->getAddressBooksForUser('principals\/user...')\n#12 \/var\/www\/owncloud\/apps\/dav\/lib\/Migration\/GenerateBirthdays.php(66): OCA\\DAV\\CalDAV\\BirthdayService->syncUser('ppaul')\n#13 \/var\/www\/owncloud\/lib\/private\/User\/Manager.php(359): OCA\\DAV\\Migration\\GenerateBirthdays->OCA\\DAV\\Migration\\{closure}(Object(OC\\User\\User))\n#14 \/var\/www\/owncloud\/apps\/dav\/lib\/Migration\/GenerateBirthdays.php(67): OC\\User\\Manager->callForAllUsers(Object(Closure))\n#15 \/var\/www\/owncloud\/lib\/private\/Repair.php(88): OCA\\DAV\\Migration\\GenerateBirthdays->run(Object(OC\\Repair))\n#16 \/var\/www\/owncloud\/lib\/private\/Migration\/BackgroundRepair.php(102): OC\\Repair->run()\n#17 \/var\/www\/owncloud\/lib\/private\/BackgroundJob\/Job.php(52): OC\\Migration\\BackgroundRepair->run(Array)\n#18 \/var\/www\/owncloud\/lib\/private\/BackgroundJob\/TimedJob.php(53): OC\\BackgroundJob\\Job->execute(Object(OC\\BackgroundJob\\JobList), Object(OC\\Log))\n#19 \/var\/www\/owncloud\/lib\/private\/Migration\/BackgroundRepair.php(63): OC\\BackgroundJob\\TimedJob->execute(Object(OC\\BackgroundJob\\JobList), Object(OC\\Log))\n#20 \/var\/www\/owncloud\/cron.php(146): OC\\Migration\\BackgroundRepair->execute(Object(OC\\BackgroundJob\\JobList), Object(OC\\Log))\n#21 {main}","File":"\/var\/www\/owncloud\/apps\/user_ldap\/lib\/LDAP.php","Line":284}`
#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by glitchsys** [comment]
I'm having the same exact issue. I'll enter phone numbers, names, addresses. It may look fine but then when I move on to the next contact and then go back to the contact only bits of the information got saved. Half the phone number or name or address is cut off or just the last character or two. It's very strange.

**Comment by glitchsys** [comment]
Hey 0-kaladin, I'm curious about something. Do you happen to have the "LDAP user and group backend  0.9.0" App/Module enabled? If you do, just as a test, can you disable the LDAP module and logging in as a non-ldap user/local admin and try making some changes to the contacts?

**Comment by yvanmoriame** [comment]
Hi, 
I'm having same issue ...         
This issue has been reported since january   !!!     Nobody there ???
Firefox V = 54.0.1 (32 bits)
OC = ownCloud 9.1.6 (stable)
Contacts App = 1.5.1 
PHP = 7.0.19-1

**Comment by tony5** [comment]
just a thought but look at your apache2.conf and see if there is anything related to etags.
maybe something like "FileETag None" if so comment it out and try that.

**Comment by simme332** [comment]
Bypassing the DNS at Cloudflare solved this problem for me. It has nothing to do with any Javascript compression or other speed up functions. Not sure what the problem is.
