### ISSUE TITLE
Importing vcf contacts list stucks at 4%

### ISSUE THREAD

**Issue by Dr34ml4and3r** [owncloud/contacts#587]
I'm trying to manually transfer all my contacts(581) from my iphone to the addressbook of my owncloud.
From the iphone I exported them in vcf format,the importing process in owncloud stops at 4% and in the addressbook imports only 26 contacts.
The syncronization process is working fine, I can add,edit,delete contact in owncloud and it syncronizes with my iphone addressbook and viceversa.
The only problem is with importing the contacts.

Is it a bug?

### Actual behaviour
The import process stucks at 4%.

### Server configuration
**Operating system**:
Linux
**Web server:**
Apache 2.2.31

**Database:**
Mysql 5.5.51-38.2
**PHP version:**
5.4.45
**ownCloud version:** (see ownCloud admin page)
9.1.4
**Contacts version:** (see ownCloud apps page)
1.5.1
**Updated from an older ownCloud or fresh install:**
fresh install

**List of activated apps:**
Calendar
Contacts

**Comment by Dr34ml4and3r** [comment]
In owncloud.log I found this errors when importing contacts in owncloud

{"reqId":"WPO8tsC5BHkAAS5c8vgAAACH","remoteAddr":"84.232.195.215","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured, No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/home2\\\/host\\\/public_html\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/home2\\\/host\\\/public_html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/home2\\\/host\\\/public_html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/home2\\\/host\\\/public_html\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Server.php(178): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/home2\\\/host\\\/public_html\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(30): OCA\\\\DAV\\\\Server->exec()\\n#6 \\\/home2\\\/host\\\/public_html\\\/owncloud\\\/remote.php(164): require_once('\\\/home2\\\/host\\\/...')\\n#7 {main}\",\"File\":\"\\\/home2\\\/host\\\/public_html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":188,\"User\":false}","level":0,"time":"2017-04-16T18:49:27+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/dav\/principals\/users\/Administrator\/","user":"--"}
{"reqId":"WPO8uMC5BHkAAS5c8yQAAACo","remoteAddr":"84.232.195.215","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured, No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/home2\\\/host\\\/public_html\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/home2\\\/host\\\/public_html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/home2\\\/host\\\/public_html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/home2\\\/host\\\/public_html\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Server.php(178): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/home2\\\/host\\\/public_html\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(30): OCA\\\\DAV\\\\Server->exec()\\n#6 \\\/home2\\\/host\\\/public_html\\\/owncloud\\\/remote.php(164): require_once('\\\/home2\\\/host\\\/...')\\n#7 {main}\",\"File\":\"\\\/home2\\\/host\\\/public_html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":188,\"User\":false}","level":0,"time":"2017-04-16T18:49:28+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/dav\/addressbooks\/users\/Administrator\/","user":"--"}
{"reqId":"WPO@q8C5BHkAAaL2cwwAAACz","remoteAddr":"84.232.195.215","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured, No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/home2\\\/host\\\/public_html\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/home2\\\/host\\\/public_html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/home2\\\/host\\\/public_html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/home2\\\/host\\\/public_html\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Server.php(178): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/home2\\\/host\\\/public_html\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(30): OCA\\\\DAV\\\\Server->exec()\\n#6 \\\/home2\\\/host\\\/public_html\\\/owncloud\\\/remote.php(164): require_once('\\\/home2\\\/host\\\/...')\\n#7 {main}\",\"File\":\"\\\/home2\\\/host\\\/public_html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":188,\"User\":\"Administrator\"}","level":0,"time":"2017-04-16T18:57:47+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/dav\/calendars\/Administrator\/","user":"Administrator"}
{"reqId":"WPPBqcC5BHkAACDgLFcAAACY","remoteAddr":"84.232.195.215","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured, No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/home2\\\/host\\\/public_html\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/home2\\\/host\\\/public_html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/home2\\\/host\\\/public_html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/home2\\\/host\\\/public_html\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Server.php(178): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/home2\\\/host\\\/public_html\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(30): OCA\\\\DAV\\\\Server->exec()\\n#6 \\\/home2\\\/host\\\/public_html\\\/owncloud\\\/remote.php(164): require_once('\\\/home2\\\/host\\\/...')\\n#7 {main}\",\"File\":\"\\\/home2\\\/host\\\/public_html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":188,\"User\":false}","level":0,"time":"2017-04-16T19:10:33+00:00","method":"REPORT","url":"\/owncloud\/remote.php\/dav\/addressbooks\/users\/Administrator\/Iphone\/","user":"--"}
{"reqId":"WPPBrsC5BHkAACoaQecAAAGi","remoteAddr":"84.232.195.215","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured, No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/home2\\\/host\\\/public_html\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/home2\\\/host\\\/public_html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/home2\\\/host\\\/public_html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/home2\\\/host\\\/public_html\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Server.php(178): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/home2\\\/host\\\/public_html\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(30): OCA\\\\DAV\\\\Server->exec()\\n#6 \\\/home2\\\/host\\\/public_html\\\/owncloud\\\/remote.php(164): require_once('\\\/home2\\\/host\\\/...')\\n#7 {main}\",\"File\":\"\\\/home2\\\/host\\\/public_html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":188,\"User\":false}","level":0,"time":"2017-04-16T19:10:38+00:00","method":"REPORT","url":"\/owncloud\/remote.php\/dav\/addressbooks\/users\/Administrator\/contacts\/","user":"--"}
{"reqId":"WPPBsMC5BHkAACoaQjEAAAGl","remoteAddr":"84.232.195.215","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured, No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/home2\\\/host\\\/public_html\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/home2\\\/host\\\/public_html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/home2\\\/host\\\/public_html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/home2\\\/host\\\/public_html\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Server.php(178): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/home2\\\/host\\\/public_html\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(30): OCA\\\\DAV\\\\Server->exec()\\n#6 \\\/home2\\\/host\\\/public_html\\\/owncloud\\\/remote.php(164): require_once('\\\/home2\\\/host\\\/...')\\n#7 {main}\",\"File\":\"\\\/home2\\\/host\\\/public_html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":188,\"User\":false}","level":0,"time":"2017-04-16T19:10:40+00:00","method":"OPTIONS","url":"\/owncloud\/remote.php\/dav\/principals\/users\/Administrator\/","user":"--"}

**Comment by DeepDiver1975** [comment]
all these 'No 'Authorization: Basic' header found.' messages are not related. I suspect an issue in the front end code. Please have a look at the browser console. THX

**Comment by blausand** [comment]
Same with me. Different address books stuck at different percentages.
Leaving the browser open to let import proceed in the background.
# Actual behaviour
Firefox crashes during the import process (at 60%).
After restart, the number of contacts online ist 383, while Notepad++ finds 702 instances of `BEGIN:VCARD` in the file. This matches 60%...
The Contact #383 and #384 seem unsuspicious to me:
```
BEGIN:VCARD
VERSION:2.1
N;CHARSET=UTF-8:Soares;Gonçalo;;;
FN;CHARSET=UTF-8:"Gonçalo Soares"
ADR;HOME=;POSTAL=;CHARSET=UTF-8:;;;;;;pt
EMAIL;PREF=;INTERNET=:goncalo.s.soares@gmail.com
CATEGORIES;CHARSET=UTF-8:CouchSurfer
UID:33d265da-ea21-401f-8fbd-526ca4fb0f3e
END:VCARD
BEGIN:VCARD
VERSION:2.1
N;CHARSET=UTF-8:Behrends;Jakob;;;
FN;CHARSET=UTF-8:Jakob Behrends
NICKNAME;CHARSET=UTF-8:jake
TEL;CELL=;VOICE=:+49 179 7*****2
EMAIL;PREF=;INTERNET=:Tschoepler@*****.de
EMAIL;INTERNET=:hello@*****.net
NOTE;CHARSET=UTF-8:tschoepler@*****.de
UID:47d48c13-6c99-41d0-a736-bf3f9365827d
END:VCARD
```
# Server configuration
## Operating system:
Linux Mint
Web server:
Apache 2.4.7

Database:
Mysql 5.5.51-38.2
PHP version:
5.5.9-1ubuntu4.21
ownCloud version: (see ownCloud admin page)
9.1.6
Contacts version: (see ownCloud apps page)
1.5.1
Updated from an older ownCloud or fresh install:
Updated.

List of activated apps:
Calendar, Contacts, Gallery, Tasks, Notes, Deleted Files, Federation, Collaborative Tags, ...

**Comment by Sebasaddam** [comment]
If you are unable to import vcf contacts , you can use **vCard Export Import** software. This software help you to import your vcf contacts list .
More Info :- http://www.osttopstapp.com/vcard-export-import.html
