### ISSUE TITLE
Fatal error loading Contacts app if sharing is turned off

### ISSUE THREAD

**Issue by gstuartj** [owncloud/contacts#808]
If sharing is turned off on a clean installation of Owncloud 8.0 (8.0.0-5 release package, Ubuntu) then the contacts app will not fully load and several bugs are introduced. Contacts will load your contact data in the right pane, but the left pane never finishes loading, displays the spinner, and will not display contact groups or allow their creation. The following is an excerpt of the error from the logs.

Fatal	index	Exception: {"Message":"Sharing backend for contact not found","Code":0,"Trace":"#0 \/var\/www\/owncloud\/lib\/private\/tags.php(122): OC\\Share\\Share::getBackend('contact')\n#1 \/var\/www\/owncloud\/lib\/private\/tagmanager.php(81): OC\\Tags->__construct(Object(OC\\Tagging\\TagMapper), '<username>', 'contact', Array, true)\n#2 \/var\/www\/owncloud\/apps\/contacts\/lib\/dispatcher.php(88): OC\\TagManager->load('contact', Array, true)\n#3 \/var\/www\/owncloud\/3rdparty\/pimple\/pimple\/src\/Pimple\/Container.php(112): OCA\\Contacts\\Dispatcher->OCA\\Contacts\\{closure}(Object(OC\\AppFramework\\DependencyInjection\\DIContainer))\n#4 \/var\/www\/owncloud\/lib\/private\/appframework\/utility\/simplecontainer.php(91): Pimple\\Container->offsetGet('GroupController')\n#5 \/var\/www\/owncloud\/lib\/private\/appframework\/app.php(86): OC\\AppFramework\\Utility\\SimpleContainer->query('GroupController')\n#6 \/var\/www\/owncloud\/lib\/public\/appframework\/app.php(125): OC\\AppFramework\\App::main('GroupController', 'addGroup', Object(OC\\AppFramework\\DependencyInjection\\DIContainer))\n#7 \/var\/www\/owncloud\/apps\/contacts\/appinfo\/routes.php(395): OCP\\AppFramework\\App->dispatch('GroupController', 'addGroup')\n#8 [internal function]: OC\\Route\\Router->OCA\\Contacts\\{closure}(Array)\n#9 \/var\/www\/owncloud\/lib\/private\/route\/router.php(250): call_user_func(Object(Closure), Array)\n#10 \/var\/www\/owncloud\/lib\/base.php(763): OC\\Route\\Router->match('\/apps\/contacts\/...')\n#11 \/var\/www\/owncloud\/index.php(36): OC::handleRequest()\n#12 {main}","File":"\/var\/www\/owncloud\/lib\/private\/share\/share.php","Line":1226}	2015-02-10T15:35:45+00:00
Error	OCP\Share	Sharing backend for contact not found	2015-02-10T15:35:45+00:00

**Comment by ConiKost** [comment]
I can confirm this bug.

**Comment by SourcemakerHD** [comment]
I can confirm this bug, too.

**Comment by xerocuil** [comment]
I'm also getting this bug.

**Comment by RealRancor** [comment]
Some reports at the forum:

https://forum.owncloud.org/viewtopic.php?f=31&t=28018
https://forum.owncloud.org/viewtopic.php?f=21&t=27490
https://forum.owncloud.org/viewtopic.php?f=31&t=26880

**Comment by rfc2822** [comment]
Can confirm this issue with a fresh 8.1.0 installation.

**Comment by crsqq** [comment]
This issue still exists in ownCloud 8.2.1 (stable).

Workaround: enable "Allow apps to use the Share API". (even if you have disabled the "share files" app)

**Comment by RealRancor** [comment]
@crsqq As this issue is still open its unlikely that this got fixed. Furthermore apps like calendar and contacts apps are not updated by updating oC itself.
