### ISSUE TITLE
CLI backup of contacts (cardDAV) does not work anymore

### ISSUE THREAD

**Issue by ontheair81** [owncloud/contacts#836]
Hello,

I am running a cronjob every night to backup the cardDAV contacts / addressbook to a .vcf-file on my server. This was working very well with prior versions of ownCloud, but it is not working since upgrading to ownCloud 8.0.0.

This is the command of the cronjob:
wget --auth-no-challenge --no-clobber --http-user=[USERNAME] --http-password=[PASSWORD] -O [LOCAL/PATH/TO/STORE/VCF]date +\%Y\%m\%d-MyContacts.vcf "http://localhost/owncloud/index.php/apps/contacts/addressbook/local/18/export"

The command now returns this error:
HTTP-Anforderung gesendet, warte auf Antwort... 500 Internal Server Error
2015-02-23 08:24:13 FEHLER 500: Internal Server Error.

Webserver log:
127.0.0.1 localhost - [23/Feb/2015:01:40:02 +0100] "GET /owncloud/index.php/apps/contacts/addressbook/local/18/export HTTP/1.1" 500 10559 "-" "Wget/1.13.4 (linux-gnueabihf)"

But when I visit this URL with a browser, I can log in and download the .vcf-file:
http://myserver.net/owncloud/index.php/apps/contacts/addressbook/local/18/export

Also everything else is working. Just the backup via command line is not working.

This was discussed and confirmed by another user in the ownCloud-Forums:
https://forum.owncloud.org/viewtopic.php?f=31&t=26640&p=80594#p80594

(This is my first issue in GitHub, so sorry if I missed some information needed. In this case just reply and I will do my best.)

**Comment by basc** [comment]
Same for me since Owncloud 8.0. Version 7.0.4 was working fine.

curl -s -u $HTTPUSER:$HTTPPASS -o cal.ics "http://myserver.net/index.php/apps/contacts/addressbook/local/3/export"

Here is the exception from file owncloud.log
```
{
    "reqId": "6237b2b5253749684a22c72267a00b79",
    "remoteAddr": "x.x.x.x",
    "app": "index",
    "message": "Exception: 
		{
			"Message": "Session has been closed - no further changes to the session as allowed",
			"Code": 0,
			"Trace": "#0 /var/www/vhosts/xxx.de/owncloud/lib/private/session/internal.php(36): OC\Session\Internal->validateSession()\
					#1 /var/www/vhosts/xxx.de/owncloud/lib/private/util.php(983): OC\Session\Internal->set('requesttoken', 'DPLIr5Z1TJ2v6VE...')\
					#2 /var/www/vhosts/xxx.de/owncloud/lib/public/util.php(373): OC_Util::callRegister()\
					#3 /var/www/vhosts/xxx.de/owncloud/lib/private/appframework/middleware/security/securitymiddleware.php(116): OCP\Util::callRegister()\
					#4 /var/www/vhosts/xxx.de/owncloud/lib/private/appframework/middleware/middlewaredispatcher.php(90): OC\AppFramework\Middleware\Security\SecurityMiddleware->beforeController(Object(OCA\Contacts\Controller\ExportController), 'exportAddressBo...')\
					#5 /var/www/vhosts/xxx.de/owncloud/lib/private/appframework/http/dispatcher.php(85): OC\AppFramework\Middleware\MiddlewareDispatcher->beforeController(Object(OCA\Contacts\Controller\ExportController), 'exportAddressBo...')\
					#6 /var/www/vhosts/xxx.de/owncloud/lib/private/appframework/app.php(97): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Contacts\Controller\ExportController), 'exportAddressBo...')\
					#7 /var/www/vhosts/xxx.de/owncloud/lib/public/appframework/app.php(125): OC\AppFramework\App::main('ExportControlle...', 'exportAddressBo...', Object(OC\AppFramework\DependencyInjection\DIContainer))\
					#8 /var/www/vhosts/xxx.de/owncloud/apps/contacts/appinfo/routes.php(252): OCP\AppFramework\App->dispatch('ExportControlle...', 'exportAddressBo...')\
					#9 [internal function]: OC\Route\Router->OCA\Contacts\{closure}(Array)\
					#10 /var/www/vhosts/xxx.de/owncloud/lib/private/route/router.php(250): call_user_func(Object(Closure), Array)\
					#11 /var/www/vhosts/xxx.de/owncloud/lib/base.php(763): OC\Route\Router->match('/apps/contacts/...')\
					#12 /var/www/vhosts/xxx.de/owncloud/index.php(36): OC::handleRequest()\
					#13 {main}",
			"File": "/var/www/vhosts/xxx.de/owncloud/lib/private/session/internal.php",
			"Line": 87
		}
	",
    "level": 4,
    "time": "2015-02-27T10:38:29+00:00"
}
```

Backup calendars with following url is still working with Owncloud 8.0
http://myserver.net/index.php/apps/calendar/export.php?calid=4

**Comment by RealRancor** [comment]
Hi,

very likely a duplicate of https://github.com/owncloud/contacts/issues/805

Use the correct URL instead and it should work:

https://doc.owncloud.org/server/8.0/user_manual/pim/contacts.html#special-carddav-urls

**Comment by ontheair81** [comment]
Thats right, thank you!

I just used the URL, presented by the contacts app inside ownCloud 8.0, and thats the old URL.
Maybe this behaviour should be changed?

Anyway, thanks for referencing to the other issue.

**Comment by RealRancor** [comment]
Hi,

i don't think that this link was ever intended to be used from command line. The URL is still fine when using from the WebGUI so there is probably no change needed for it.

**Comment by tigerfoot** [comment]
The recommended url in documentation is fine with 2 exceptions.
you need to know your username (can be tricky with ldap connector and uuid)
then you need all agenda or addressbook name used for a user.

If the user change the name, the backup will not more occur.

For a real admins and user friendly safety, there's should be possible to have the following.
An automatic export (configurable) happening every (configurable) time intervall for all agenda and addressbook to a (configurable) destination.
If the destination is somewhere in the file data document place, a user that delete an agenda or a addressbook will be able to restore it afterward with the last backup, even without the help of an admin.

**Comment by RealRancor** [comment]
@tigerfoot I think that needs a new issue as its more a new feature in my opinion.
