### ISSUE TITLE
No basic authentication headers were found

### ISSUE THREAD

**Issue by SunboX** [owncloud/contacts#856]
Using ownCloud 8.0.2 and the OS X 10.10.2 Contacts App I'm getting this Error when trying to delete a batch of contacts (150 contacts):

```
 Debug 	carddav 	Exception: {"Message":"No basic authentication headers were found","Code":0,"Trace":"#0 \/share3\/www\/lib\/private\/connector\/sabre\/auth.php(126): Sabre\\DAV\\Auth\\Backend\\AbstractBasic->authenticate(Object(Sabre\\DAV\\Server), 'ownCloud')\n#1 \/share3\/www\/lib\/private\/connector\/sabre\/auth.php(106): OC_Connector_Sabre_Auth->auth(Object(Sabre\\DAV\\Server), 'ownCloud')\n#2 \/share3\/www\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Auth\/Plugin.php(108): OC_Connector_Sabre_Auth->authenticate(Object(Sabre\\DAV\\Server), 'ownCloud')\n#3 [internal function]: Sabre\\DAV\\Auth\\Plugin->beforeMethod('DELETE', 'addressbooks\/Su...')\n#4 \/share3\/www\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Server.php(433): call_user_func_array(Array, Array)\n#5 \/share3\/www\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Server.php(455): Sabre\\DAV\\Server->broadcastEvent('beforeMethod', Array)\n#6 \/share3\/www\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Server.php(214): Sabre\\DAV\\Server->invokeMethod('DELETE', 'addressbooks\/Su...')\n#7 \/share3\/www\/apps\/contacts\/appinfo\/remote.php(88): Sabre\\DAV\\Server->exec()\n#8 \/share3\/www\/remote.php(54): require_once('\/share3\/www\/app...')\n#9 {main}","File":"\/share3\/www\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Auth\/Backend\/AbstractBasic.php","Line":73} 
```

**Comment by SunboX** [comment]
Btw, initial sync works fine. :/ just happens if I try to delete many contacts

**Comment by RealRancor** [comment]
Could be related or a duplicate of: https://github.com/owncloud/core/issues/14510

**Comment by raimund-schluessler** [comment]
I see this issue under contacts v0.4.0 with oC8.1.

```
Exception: {"Message":"HTTP\/1.1 401 No basic authentication headers were 
found","Code":0,"Trace":"#0 \/usr\/www\/owncloud\/lib\/private\/connector\/sabre\/auth.php(149): 
Sabre\\DAV\\Auth\\Backend\\AbstractBasic->authenticate(Object(Sabre\\DAV\\Server), 
'ownCloud')\n#1 \/usr\/www\/owncloud\/lib\/private\/connector\/sabre\/auth.php(122): OC\\Connector
\\Sabre\\Auth->auth(Object(Sabre\\DAV\\Server), 'ownCloud')\n#2 \/usr\/www\/owncloud\/3rdparty
\/sabre\/dav\/lib\/DAV\/Auth\/Plugin.php(118): OC\\Connector\\Sabre
\\Auth->authenticate(Object(Sabre\\DAV\\Server), 'ownCloud')\n#3 [internal function]: Sabre\\DAV
\\Auth\\Plugin->beforeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 
\/usr\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): 
call_user_func_array(Array, Array)\n#5 \/usr\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV
\/Server.php(456): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)\n#6 \/usr\
/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV
\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#7 \/usr\
/www\/owncloud\/apps\/contacts\/appinfo\/remote.php(84): Sabre\\DAV\\Server->exec()\n#8 \/usr\
/www\/owncloud\/remote.php(132): require_once('\/usr\/www\/ownclo...')\n#9 {main}","File":"\/usr
\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Auth\/Backend\/AbstractBasic.php","Line":70}
```

and a very similar problems with calendar: https://github.com/owncloud/calendar/issues/844
