### ISSUE TITLE
RuntimeException

### ISSUE THREAD

**Issue by txt-file** [owncloud/contacts#974]
```
owncloud@Cubian:~/htdocs$ php5 occ app:list
An unhandled exception has been thrown:
exception 'RuntimeException' with message 'image not found: image:contacts.svg webroot: serverroot:/home/owncloud/htdocs' in /home/owncloud/htdocs/lib/private/urlgenerator.php:189
Stack trace:
#0 /home/owncloud/htdocs/lib/public/util.php(418): OC\URLGenerator->imagePath('contacts', 'contacts.svg')
#1 /home/owncloud/htdocs/apps/contacts/appinfo/app.php(19): OCP\Util::imagePath('contacts', 'contacts.svg')
#2 /home/owncloud/htdocs/lib/private/app.php(139): require_once('/home/owncloud/...')
#3 /home/owncloud/htdocs/lib/private/app.php(120): OC_App::requireAppFile('contacts')
#4 /home/owncloud/htdocs/lib/private/app.php(99): OC_App::loadApp('contacts')
#5 /home/owncloud/htdocs/lib/private/console/application.php(56): OC_App::loadApps()
#6 /home/owncloud/htdocs/console.php(67): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /home/owncloud/htdocs/occ(11): require_once('/home/owncloud/...')
#8 {main}
owncloud@Cubian:~/htdocs$ php5 occ app:disable contacts
An unhandled exception has been thrown:
exception 'RuntimeException' with message 'image not found: image:contacts.svg webroot: serverroot:/home/owncloud/htdocs' in /home/owncloud/htdocs/lib/private/urlgenerator.php:189
Stack trace:
#0 /home/owncloud/htdocs/lib/public/util.php(418): OC\URLGenerator->imagePath('contacts', 'contacts.svg')
#1 /home/owncloud/htdocs/apps/contacts/appinfo/app.php(19): OCP\Util::imagePath('contacts', 'contacts.svg')
#2 /home/owncloud/htdocs/lib/private/app.php(139): require_once('/home/owncloud/...')
#3 /home/owncloud/htdocs/lib/private/app.php(120): OC_App::requireAppFile('contacts')
#4 /home/owncloud/htdocs/lib/private/app.php(99): OC_App::loadApp('contacts')
#5 /home/owncloud/htdocs/lib/private/console/application.php(56): OC_App::loadApps()
#6 /home/owncloud/htdocs/console.php(67): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /home/owncloud/htdocs/occ(11): require_once('/home/owncloud/...')
#8 {main}owncloud@Cubian:~/htdocs$
```
I had owncloud version 7.0.7 running and after upgrading to 8.0.5 the contacts and calendar and bookmark apps have been disabled. I was unable to enable it again and tried an upgrade to 8.1. Since clicking the "enable" button of contacts app I get this error.

**Comment by DeepDiver1975** [comment]
does apps/contacts/img/contacts.svg exist on your installation?

**Comment by txt-file** [comment]
I now tried with a fresh owncloud install (using my previous data dir). So installing owncloud and then enabled the contacts application. It is shown as enabled in „apps“. Then running
```
owncloud@Cubian:~/owncloud$ php5 ./occ upgrade
ownCloud or one of the apps require upgrade - only a limited number of commands are available
Turned on maintenance mode
Checked database schema update
Checked database schema update for apps
Updated database
Updating <contacts> ...
RuntimeException: image not found: image:contacts.svg webroot: serverroot:/home/owncloud/owncloud
Update failed
Maintenance mode is kept active
owncloud@Cubian:~/owncloud$ find ./ -name contacts.svg
owncloud@Cubian:~/owncloud$ 
```
and the problems start.

**Comment by DeepDiver1975** [comment]
How did you install the contracts app?

**Comment by txt-file** [comment]
via the owncloud webinterface and the „Apps“-application

**Comment by DeepDiver1975** [comment]
Really strange - the zips contain the svgs - https://github.com/owncloud/contacts/releases

Fell free to grab the file from git or the archives
