### ISSUE TITLE
can not sync contacts since last upgrade owncloud 8.1.0-2

### ISSUE THREAD

**Issue by ka223** [owncloud/contacts#983]
Receive "405 Method not allowed" via caldav.

Error at owncloud (8.1.0-2) with contacts (0.4.0.0):

```
Fatal	index	Exception: {"Exception":"Symfony\\Component\\Routing\\Exception\\RouteNotFoundException","Message":"Unable to generate a URL for the named route \"contacts_index\" as such route does not exist.","Code":0,"Trace":"#0 \/var\/www\/owncloud\/lib\/private\/route\/router.php(306): Symfony\\Component\\Routing\\Generator\\UrlGenerator->generate('contacts_index', Array, false)\n#1 \/var\/www\/owncloud\/lib\/private\/urlgenerator.php(65): OC\\Route\\Router->generate('contacts_index', Array)\n#2 \/var\/www\/owncloud\/lib\/private\/helper.php(139): OC\\URLGenerator->linkToRoute('contacts_index', Array)\n#3 \/var\/www\/owncloud\/lib\/public\/util.php(306): OC_Helper::linkToRoute('contacts_index', Array)\n#4 \/var\/www\/owncloud\/apps\/contacts\/appinfo\/app.php(18): OCP\\Util::linkToRoute('contacts_index')\n#5 \/var\/www\/owncloud\/lib\/private\/app.php(389): require('\/var\/www\/ownclo...')\n#6 \/var\/www\/owncloud\/settings\/ajax\/navigationdetect.php(29): OC_App::getAppNavigationEntries('contacts')\n#7 \/var\/www\/owncloud\/lib\/private\/route\/route.php(154) : runtime-created function(1): require_once('\/var\/www\/ownclo...')\n#8 [internal function]: __lambda_func(Array)\n#9 \/var\/www\/owncloud\/lib\/private\/route\/router.php(274): call_user_func('\\x00lambda_379', Array)\n#10 \/var\/www\/owncloud\/lib\/base.php(867): OC\\Route\\Router->match('\/settings\/ajax\/...')\n#11 \/var\/www\/owncloud\/index.php(40): OC::handleRequest()\n#12 {main}","File":"\/var\/www\/owncloud\/3rdparty\/symfony\/routing\/Symfony\/Component\/Routing\/Generator\/UrlGenerator.php","Line":134}	2015-07-12T11:25:41+00:00
```

**Comment by nazgul77** [comment]
Got this error message when upgrading to 8.1.4
"Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "contacts_index" as such route does not exist."
It asks to report the issue

**Comment by kropveld** [comment]
Same problem here on Ubuntu server 14.04.3 LTS

**Comment by gvde** [comment]
1. Use the template from the contribution guidelines for issue submissions.

2. Update contacts app.

**Comment by bugsyb** [comment]
Try to repair in maintenance mode, it did help me:
sudo -u www-data php <path_to_your_installation>/occ maintenance:repair

**Comment by kropveld** [comment]
I solved this by typing `sudo -u www-data php /occ upgrade`
(previously I did the final upgrade from the web-interface)
